[2019-07-01 16:56:53,418] [ERROR] [buffer.py] [86] - pushall pipe execute exception: Error 110 connecting to redis-bigdatacache-1.istarshine.net.cn:6379. Connection timed out.
Traceback (most recent call last):
  File "/work/spider/data_buffer/buffer.py", line 84, in pushall
    pipe.execute()
  File "/usr/local/python-2.7.13/lib/python2.7/site-packages/redis/client.py", line 2641, in execute
    return execute(conn, stack, raise_on_error)
  File "/usr/local/python-2.7.13/lib/python2.7/site-packages/redis/client.py", line 2495, in _execute_transaction
    connection.send_packed_command(all_cmds)
  File "/usr/local/python-2.7.13/lib/python2.7/site-packages/redis/connection.py", line 538, in send_packed_command
    self.connect()
  File "/usr/local/python-2.7.13/lib/python2.7/site-packages/redis/connection.py", line 442, in connect
    raise ConnectionError(self._error_message(e))
ConnectionError: Error 110 connecting to redis-bigdatacache-1.istarshine.net.cn:6379. Connection timed out.
[2019-07-01 17:14:08,966] [ERROR] [buffer.py] [86] - pushall pipe execute exception: Error 110 connecting to redis-bigdatacache-1.istarshine.net.cn:6379. Connection timed out.
Traceback (most recent call last):
  File "/work/spider/data_buffer/buffer.py", line 84, in pushall
    pipe.execute()
  File "/usr/local/python-2.7.13/lib/python2.7/site-packages/redis/client.py", line 2641, in execute
    return execute(conn, stack, raise_on_error)
  File "/usr/local/python-2.7.13/lib/python2.7/site-packages/redis/client.py", line 2495, in _execute_transaction
    connection.send_packed_command(all_cmds)
  File "/usr/local/python-2.7.13/lib/python2.7/site-packages/redis/connection.py", line 538, in send_packed_command
    self.connect()
  File "/usr/local/python-2.7.13/lib/python2.7/site-packages/redis/connection.py", line 442, in connect
    raise ConnectionError(self._error_message(e))
ConnectionError: Error 110 connecting to redis-bigdatacache-1.istarshine.net.cn:6379. Connection timed out.
[2019-07-01 18:02:09,694] [ERROR] [buffer.py] [86] - pushall pipe execute exception: Error 110 connecting to redis-bigdatacache-1.istarshine.net.cn:6379. Connection timed out.
Traceback (most recent call last):
  File "/work/spider/data_buffer/buffer.py", line 84, in pushall
    pipe.execute()
  File "/usr/local/python-2.7.13/lib/python2.7/site-packages/redis/client.py", line 2641, in execute
    return execute(conn, stack, raise_on_error)
  File "/usr/local/python-2.7.13/lib/python2.7/site-packages/redis/client.py", line 2495, in _execute_transaction
    connection.send_packed_command(all_cmds)
  File "/usr/local/python-2.7.13/lib/python2.7/site-packages/redis/connection.py", line 538, in send_packed_command
    self.connect()
  File "/usr/local/python-2.7.13/lib/python2.7/site-packages/redis/connection.py", line 442, in connect
    raise ConnectionError(self._error_message(e))
ConnectionError: Error 110 connecting to redis-bigdatacache-1.istarshine.net.cn:6379. Connection timed out.
[2019-07-01 19:32:53,206] [ERROR] [buffer.py] [86] - pushall pipe execute exception: Error 110 connecting to redis-bigdatacache-1.istarshine.net.cn:6379. Connection timed out.
Traceback (most recent call last):
  File "/work/spider/data_buffer/buffer.py", line 84, in pushall
    pipe.execute()
  File "/usr/local/python-2.7.13/lib/python2.7/site-packages/redis/client.py", line 2641, in execute
    return execute(conn, stack, raise_on_error)
  File "/usr/local/python-2.7.13/lib/python2.7/site-packages/redis/client.py", line 2495, in _execute_transaction
    connection.send_packed_command(all_cmds)
  File "/usr/local/python-2.7.13/lib/python2.7/site-packages/redis/connection.py", line 538, in send_packed_command
    self.connect()
  File "/usr/local/python-2.7.13/lib/python2.7/site-packages/redis/connection.py", line 442, in connect
    raise ConnectionError(self._error_message(e))
ConnectionError: Error 110 connecting to redis-bigdatacache-1.istarshine.net.cn:6379. Connection timed out.
[2019-07-01 20:02:12,510] [ERROR] [buffer.py] [86] - pushall pipe execute exception: Error 110 connecting to redis-bigdatacache-1.istarshine.net.cn:6379. Connection timed out.
Traceback (most recent call last):
  File "/work/spider/data_buffer/buffer.py", line 84, in pushall
    pipe.execute()
  File "/usr/local/python-2.7.13/lib/python2.7/site-packages/redis/client.py", line 2641, in execute
    return execute(conn, stack, raise_on_error)
  File "/usr/local/python-2.7.13/lib/python2.7/site-packages/redis/client.py", line 2495, in _execute_transaction
    connection.send_packed_command(all_cmds)
  File "/usr/local/python-2.7.13/lib/python2.7/site-packages/redis/connection.py", line 538, in send_packed_command
    self.connect()
  File "/usr/local/python-2.7.13/lib/python2.7/site-packages/redis/connection.py", line 442, in connect
    raise ConnectionError(self._error_message(e))
ConnectionError: Error 110 connecting to redis-bigdatacache-1.istarshine.net.cn:6379. Connection timed out.
[2019-07-01 22:44:59,266] [ERROR] [buffer.py] [86] - pushall pipe execute exception: Error 110 connecting to redis-bigdatacache-1.istarshine.net.cn:6379. Connection timed out.
Traceback (most recent call last):
  File "/work/spider/data_buffer/buffer.py", line 84, in pushall
    pipe.execute()
  File "/usr/local/python-2.7.13/lib/python2.7/site-packages/redis/client.py", line 2641, in execute
    return execute(conn, stack, raise_on_error)
  File "/usr/local/python-2.7.13/lib/python2.7/site-packages/redis/client.py", line 2495, in _execute_transaction
    connection.send_packed_command(all_cmds)
  File "/usr/local/python-2.7.13/lib/python2.7/site-packages/redis/connection.py", line 538, in send_packed_command
    self.connect()
  File "/usr/local/python-2.7.13/lib/python2.7/site-packages/redis/connection.py", line 442, in connect
    raise ConnectionError(self._error_message(e))
ConnectionError: Error 110 connecting to redis-bigdatacache-1.istarshine.net.cn:6379. Connection timed out.
[2019-07-02 00:02:42,930] [ERROR] [buffer.py] [86] - pushall pipe execute exception: Error 110 connecting to redis-bigdatacache-1.istarshine.net.cn:6379. Connection timed out.
Traceback (most recent call last):
  File "/work/spider/data_buffer/buffer.py", line 84, in pushall
    pipe.execute()
  File "/usr/local/python-2.7.13/lib/python2.7/site-packages/redis/client.py", line 2641, in execute
    return execute(conn, stack, raise_on_error)
  File "/usr/local/python-2.7.13/lib/python2.7/site-packages/redis/client.py", line 2495, in _execute_transaction
    connection.send_packed_command(all_cmds)
  File "/usr/local/python-2.7.13/lib/python2.7/site-packages/redis/connection.py", line 538, in send_packed_command
    self.connect()
  File "/usr/local/python-2.7.13/lib/python2.7/site-packages/redis/connection.py", line 442, in connect
    raise ConnectionError(self._error_message(e))
ConnectionError: Error 110 connecting to redis-bigdatacache-1.istarshine.net.cn:6379. Connection timed out.
[2019-07-02 00:20:26,278] [ERROR] [buffer.py] [86] - pushall pipe execute exception: Error 110 connecting to redis-bigdatacache-1.istarshine.net.cn:6379. Connection timed out.
Traceback (most recent call last):
  File "/work/spider/data_buffer/buffer.py", line 84, in pushall
    pipe.execute()
  File "/usr/local/python-2.7.13/lib/python2.7/site-packages/redis/client.py", line 2641, in execute
    return execute(conn, stack, raise_on_error)
  File "/usr/local/python-2.7.13/lib/python2.7/site-packages/redis/client.py", line 2495, in _execute_transaction
    connection.send_packed_command(all_cmds)
  File "/usr/local/python-2.7.13/lib/python2.7/site-packages/redis/connection.py", line 538, in send_packed_command
    self.connect()
  File "/usr/local/python-2.7.13/lib/python2.7/site-packages/redis/connection.py", line 442, in connect
    raise ConnectionError(self._error_message(e))
ConnectionError: Error 110 connecting to redis-bigdatacache-1.istarshine.net.cn:6379. Connection timed out.
[2019-07-02 02:02:09,782] [ERROR] [buffer.py] [86] - pushall pipe execute exception: Error 110 connecting to redis-bigdatacache-1.istarshine.net.cn:6379. Connection timed out.
Traceback (most recent call last):
  File "/work/spider/data_buffer/buffer.py", line 84, in pushall
    pipe.execute()
  File "/usr/local/python-2.7.13/lib/python2.7/site-packages/redis/client.py", line 2641, in execute
    return execute(conn, stack, raise_on_error)
  File "/usr/local/python-2.7.13/lib/python2.7/site-packages/redis/client.py", line 2495, in _execute_transaction
    connection.send_packed_command(all_cmds)
  File "/usr/local/python-2.7.13/lib/python2.7/site-packages/redis/connection.py", line 538, in send_packed_command
    self.connect()
  File "/usr/local/python-2.7.13/lib/python2.7/site-packages/redis/connection.py", line 442, in connect
    raise ConnectionError(self._error_message(e))
ConnectionError: Error 110 connecting to redis-bigdatacache-1.istarshine.net.cn:6379. Connection timed out.
[2019-07-02 02:47:00,210] [ERROR] [buffer.py] [86] - pushall pipe execute exception: Error 110 connecting to redis-bigdatacache-1.istarshine.net.cn:6379. Connection timed out.
Traceback (most recent call last):
  File "/work/spider/data_buffer/buffer.py", line 84, in pushall
    pipe.execute()
  File "/usr/local/python-2.7.13/lib/python2.7/site-packages/redis/client.py", line 2641, in execute
    return execute(conn, stack, raise_on_error)
  File "/usr/local/python-2.7.13/lib/python2.7/site-packages/redis/client.py", line 2495, in _execute_transaction
    connection.send_packed_command(all_cmds)
  File "/usr/local/python-2.7.13/lib/python2.7/site-packages/redis/connection.py", line 538, in send_packed_command
    self.connect()
  File "/usr/local/python-2.7.13/lib/python2.7/site-packages/redis/connection.py", line 442, in connect
    raise ConnectionError(self._error_message(e))
ConnectionError: Error 110 connecting to redis-bigdatacache-1.istarshine.net.cn:6379. Connection timed out.
[2019-07-02 09:06:34,358] [ERROR] [buffer.py] [86] - pushall pipe execute exception: Error 110 connecting to redis-bigdatacache-1.istarshine.net.cn:6379. Connection timed out.
Traceback (most recent call last):
  File "/work/spider/data_buffer/buffer.py", line 84, in pushall
    pipe.execute()
  File "/usr/local/python-2.7.13/lib/python2.7/site-packages/redis/client.py", line 2641, in execute
    return execute(conn, stack, raise_on_error)
  File "/usr/local/python-2.7.13/lib/python2.7/site-packages/redis/client.py", line 2495, in _execute_transaction
    connection.send_packed_command(all_cmds)
  File "/usr/local/python-2.7.13/lib/python2.7/site-packages/redis/connection.py", line 538, in send_packed_command
    self.connect()
  File "/usr/local/python-2.7.13/lib/python2.7/site-packages/redis/connection.py", line 442, in connect
    raise ConnectionError(self._error_message(e))
ConnectionError: Error 110 connecting to redis-bigdatacache-1.istarshine.net.cn:6379. Connection timed out.
[2019-07-02 09:59:58,786] [ERROR] [buffer.py] [86] - pushall pipe execute exception: Error 110 connecting to redis-bigdatacache-1.istarshine.net.cn:6379. Connection timed out.
Traceback (most recent call last):
  File "/work/spider/data_buffer/buffer.py", line 84, in pushall
    pipe.execute()
  File "/usr/local/python-2.7.13/lib/python2.7/site-packages/redis/client.py", line 2641, in execute
    return execute(conn, stack, raise_on_error)
  File "/usr/local/python-2.7.13/lib/python2.7/site-packages/redis/client.py", line 2495, in _execute_transaction
    connection.send_packed_command(all_cmds)
  File "/usr/local/python-2.7.13/lib/python2.7/site-packages/redis/connection.py", line 538, in send_packed_command
    self.connect()
  File "/usr/local/python-2.7.13/lib/python2.7/site-packages/redis/connection.py", line 442, in connect
    raise ConnectionError(self._error_message(e))
ConnectionError: Error 110 connecting to redis-bigdatacache-1.istarshine.net.cn:6379. Connection timed out.
[2019-07-02 11:11:21,654] [ERROR] [buffer.py] [86] - pushall pipe execute exception: Error 110 connecting to redis-bigdatacache-1.istarshine.net.cn:6379. Connection timed out.
Traceback (most recent call last):
  File "/work/spider/data_buffer/buffer.py", line 84, in pushall
    pipe.execute()
  File "/usr/local/python-2.7.13/lib/python2.7/site-packages/redis/client.py", line 2641, in execute
    return execute(conn, stack, raise_on_error)
  File "/usr/local/python-2.7.13/lib/python2.7/site-packages/redis/client.py", line 2495, in _execute_transaction
    connection.send_packed_command(all_cmds)
  File "/usr/local/python-2.7.13/lib/python2.7/site-packages/redis/connection.py", line 538, in send_packed_command
    self.connect()
  File "/usr/local/python-2.7.13/lib/python2.7/site-packages/redis/connection.py", line 442, in connect
    raise ConnectionError(self._error_message(e))
ConnectionError: Error 110 connecting to redis-bigdatacache-1.istarshine.net.cn:6379. Connection timed out.
[2019-07-02 12:02:09,606] [ERROR] [buffer.py] [86] - pushall pipe execute exception: Error 110 connecting to redis-bigdatacache-1.istarshine.net.cn:6379. Connection timed out.
Traceback (most recent call last):
  File "/work/spider/data_buffer/buffer.py", line 84, in pushall
    pipe.execute()
  File "/usr/local/python-2.7.13/lib/python2.7/site-packages/redis/client.py", line 2641, in execute
    return execute(conn, stack, raise_on_error)
  File "/usr/local/python-2.7.13/lib/python2.7/site-packages/redis/client.py", line 2495, in _execute_transaction
    connection.send_packed_command(all_cmds)
  File "/usr/local/python-2.7.13/lib/python2.7/site-packages/redis/connection.py", line 538, in send_packed_command
    self.connect()
  File "/usr/local/python-2.7.13/lib/python2.7/site-packages/redis/connection.py", line 442, in connect
    raise ConnectionError(self._error_message(e))
ConnectionError: Error 110 connecting to redis-bigdatacache-1.istarshine.net.cn:6379. Connection timed out.
[2019-10-23 16:35:15,282] [ERROR] [buffer.py] [104] - buffer redis pop exception: Error 10060 connecting to 192.168.2.122:6379. ., src_data=''
Traceback (most recent call last):
  File "C:/Users/lenovo/Desktop/spider/data_buffer/buffer.py", line 100, in pop
    src_data = self.conn.lpop(self.key_name)
  File "C:\Users\lenovo\Desktop\spider\venv\lib\site-packages\redis\client.py", line 1675, in lpop
    return self.execute_command('LPOP', name)
  File "C:\Users\lenovo\Desktop\spider\venv\lib\site-packages\redis\client.py", line 836, in execute_command
    conn = self.connection or pool.get_connection(command_name, **options)
  File "C:\Users\lenovo\Desktop\spider\venv\lib\site-packages\redis\connection.py", line 1073, in get_connection
    connection.connect()
  File "C:\Users\lenovo\Desktop\spider\venv\lib\site-packages\redis\connection.py", line 544, in connect
    raise ConnectionError(self._error_message(e))
ConnectionError: Error 10060 connecting to 192.168.2.122:6379. .
[2019-12-05 15:46:05,526] [ERROR] [buffer.py] [85] - pushall pipe execute exception: Error while reading from socket: (10054, '')
Traceback (most recent call last):
  File "C:\Users\lenovo\Desktop\spider\data_buffer\buffer.py", line 83, in pushall
    pipe.execute()
  File "C:\Users\lenovo\Desktop\spider\venv\lib\site-packages\redis\client.py", line 3691, in execute
    return execute(conn, stack, raise_on_error)
  File "C:\Users\lenovo\Desktop\spider\venv\lib\site-packages\redis\client.py", line 3566, in _execute_transaction
    self.parse_response(connection, '_')
  File "C:\Users\lenovo\Desktop\spider\venv\lib\site-packages\redis\client.py", line 3650, in parse_response
    self, connection, command_name, **options)
  File "C:\Users\lenovo\Desktop\spider\venv\lib\site-packages\redis\client.py", line 853, in parse_response
    response = connection.read_response()
  File "C:\Users\lenovo\Desktop\spider\venv\lib\site-packages\redis\connection.py", line 700, in read_response
    response = self._parser.read_response()
  File "C:\Users\lenovo\Desktop\spider\venv\lib\site-packages\redis\connection.py", line 310, in read_response
    response = self._buffer.readline()
  File "C:\Users\lenovo\Desktop\spider\venv\lib\site-packages\redis\connection.py", line 242, in readline
    self._read_from_socket()
  File "C:\Users\lenovo\Desktop\spider\venv\lib\site-packages\redis\connection.py", line 209, in _read_from_socket
    (ex.args,))
ConnectionError: Error while reading from socket: (10054, '')
[2020-01-15 10:28:19,303] [ERROR] [buffer.py] [87] - json.dumps:Unterminated UTF-8 sequence when encoding string
Traceback (most recent call last):
  File "C:\Users\lenovo\Desktop\spider\data_buffer\buffer.py", line 82, in pushall
    dest_data = json.dumps(data)
OverflowError: Unterminated UTF-8 sequence when encoding string
[2020-01-15 10:30:06,697] [ERROR] [buffer.py] [87] - json.dumps:Unsupported UTF-8 sequence length when encoding string
Traceback (most recent call last):
  File "C:\Users\lenovo\Desktop\spider\data_buffer\buffer.py", line 82, in pushall
    dest_data = json.dumps(data)
OverflowError: Unsupported UTF-8 sequence length when encoding string
[2020-01-20 17:55:52,270] [ERROR] [buffer.py] [87] - json.dumps:Unterminated UTF-8 sequence when encoding string
Traceback (most recent call last):
  File "C:\Users\lenovo\Desktop\spider\data_buffer\buffer.py", line 82, in pushall
    dest_data = json.dumps(data)
OverflowError: Unterminated UTF-8 sequence when encoding string
[2020-01-22 10:56:02,362] [ERROR] [buffer.py] [87] - json.dumps:Unterminated UTF-8 sequence when encoding string
Traceback (most recent call last):
  File "C:\Users\lenovo\Desktop\spider\data_buffer\buffer.py", line 82, in pushall
    dest_data = json.dumps(data)
OverflowError: Unterminated UTF-8 sequence when encoding string
[2020-01-22 10:59:31,821] [ERROR] [buffer.py] [87] - json.dumps:Unsupported UTF-8 sequence length when encoding string
Traceback (most recent call last):
  File "C:\Users\lenovo\Desktop\spider\data_buffer\buffer.py", line 82, in pushall
    dest_data = json.dumps(data)
OverflowError: Unsupported UTF-8 sequence length when encoding string
[2020-01-22 10:59:37,428] [ERROR] [buffer.py] [87] - json.dumps:Unterminated UTF-8 sequence when encoding string
Traceback (most recent call last):
  File "C:\Users\lenovo\Desktop\spider\data_buffer\buffer.py", line 82, in pushall
    dest_data = json.dumps(data)
OverflowError: Unterminated UTF-8 sequence when encoding string
[2020-01-22 11:03:26,901] [ERROR] [buffer.py] [87] - json.dumps:Unterminated UTF-8 sequence when encoding string
Traceback (most recent call last):
  File "C:\Users\lenovo\Desktop\spider\data_buffer\buffer.py", line 82, in pushall
    dest_data = json.dumps(data)
OverflowError: Unterminated UTF-8 sequence when encoding string
[2020-01-22 11:08:31,476] [ERROR] [buffer.py] [87] - json.dumps:Unterminated UTF-8 sequence when encoding string
Traceback (most recent call last):
  File "C:\Users\lenovo\Desktop\spider\data_buffer\buffer.py", line 82, in pushall
    dest_data = json.dumps(data)
OverflowError: Unterminated UTF-8 sequence when encoding string
[2020-01-22 11:08:31,477] [ERROR] [buffer.py] [87] - json.dumps:Unterminated UTF-8 sequence when encoding string
Traceback (most recent call last):
  File "C:\Users\lenovo\Desktop\spider\data_buffer\buffer.py", line 82, in pushall
    dest_data = json.dumps(data)
OverflowError: Unterminated UTF-8 sequence when encoding string
[2020-01-22 11:08:31,479] [ERROR] [buffer.py] [87] - json.dumps:Unterminated UTF-8 sequence when encoding string
Traceback (most recent call last):
  File "C:\Users\lenovo\Desktop\spider\data_buffer\buffer.py", line 82, in pushall
    dest_data = json.dumps(data)
OverflowError: Unterminated UTF-8 sequence when encoding string
[2020-01-22 11:08:31,479] [ERROR] [buffer.py] [87] - json.dumps:Unterminated UTF-8 sequence when encoding string
Traceback (most recent call last):
  File "C:\Users\lenovo\Desktop\spider\data_buffer\buffer.py", line 82, in pushall
    dest_data = json.dumps(data)
OverflowError: Unterminated UTF-8 sequence when encoding string
[2020-01-22 11:08:31,480] [ERROR] [buffer.py] [87] - json.dumps:Unterminated UTF-8 sequence when encoding string
Traceback (most recent call last):
  File "C:\Users\lenovo\Desktop\spider\data_buffer\buffer.py", line 82, in pushall
    dest_data = json.dumps(data)
OverflowError: Unterminated UTF-8 sequence when encoding string
[2020-01-22 11:08:31,480] [ERROR] [buffer.py] [87] - json.dumps:Unterminated UTF-8 sequence when encoding string
Traceback (most recent call last):
  File "C:\Users\lenovo\Desktop\spider\data_buffer\buffer.py", line 82, in pushall
    dest_data = json.dumps(data)
OverflowError: Unterminated UTF-8 sequence when encoding string
[2020-01-22 11:08:31,482] [ERROR] [buffer.py] [87] - json.dumps:Unterminated UTF-8 sequence when encoding string
Traceback (most recent call last):
  File "C:\Users\lenovo\Desktop\spider\data_buffer\buffer.py", line 82, in pushall
    dest_data = json.dumps(data)
OverflowError: Unterminated UTF-8 sequence when encoding string
[2020-01-22 11:08:31,482] [ERROR] [buffer.py] [87] - json.dumps:Unterminated UTF-8 sequence when encoding string
Traceback (most recent call last):
  File "C:\Users\lenovo\Desktop\spider\data_buffer\buffer.py", line 82, in pushall
    dest_data = json.dumps(data)
OverflowError: Unterminated UTF-8 sequence when encoding string
[2020-01-22 11:08:31,483] [ERROR] [buffer.py] [87] - json.dumps:Unterminated UTF-8 sequence when encoding string
Traceback (most recent call last):
  File "C:\Users\lenovo\Desktop\spider\data_buffer\buffer.py", line 82, in pushall
    dest_data = json.dumps(data)
OverflowError: Unterminated UTF-8 sequence when encoding string
[2020-01-22 11:08:31,483] [ERROR] [buffer.py] [87] - json.dumps:Unterminated UTF-8 sequence when encoding string
Traceback (most recent call last):
  File "C:\Users\lenovo\Desktop\spider\data_buffer\buffer.py", line 82, in pushall
    dest_data = json.dumps(data)
OverflowError: Unterminated UTF-8 sequence when encoding string
[2020-01-22 11:08:31,483] [ERROR] [buffer.py] [87] - json.dumps:Unterminated UTF-8 sequence when encoding string
Traceback (most recent call last):
  File "C:\Users\lenovo\Desktop\spider\data_buffer\buffer.py", line 82, in pushall
    dest_data = json.dumps(data)
OverflowError: Unterminated UTF-8 sequence when encoding string
[2020-01-22 11:08:31,484] [ERROR] [buffer.py] [87] - json.dumps:Unterminated UTF-8 sequence when encoding string
Traceback (most recent call last):
  File "C:\Users\lenovo\Desktop\spider\data_buffer\buffer.py", line 82, in pushall
    dest_data = json.dumps(data)
OverflowError: Unterminated UTF-8 sequence when encoding string
[2020-01-22 11:08:31,486] [ERROR] [buffer.py] [87] - json.dumps:Unterminated UTF-8 sequence when encoding string
Traceback (most recent call last):
  File "C:\Users\lenovo\Desktop\spider\data_buffer\buffer.py", line 82, in pushall
    dest_data = json.dumps(data)
OverflowError: Unterminated UTF-8 sequence when encoding string
[2020-01-22 11:08:31,486] [ERROR] [buffer.py] [87] - json.dumps:Unterminated UTF-8 sequence when encoding string
Traceback (most recent call last):
  File "C:\Users\lenovo\Desktop\spider\data_buffer\buffer.py", line 82, in pushall
    dest_data = json.dumps(data)
OverflowError: Unterminated UTF-8 sequence when encoding string
[2020-04-21 11:15:02,903] [ERROR] [buffer.py] [87] - json.dumps:Unterminated UTF-8 sequence when encoding string
Traceback (most recent call last):
  File "C:\Users\lenovo\Desktop\spider\data_buffer\buffer.py", line 82, in pushall
    dest_data = json.dumps(data)
OverflowError: Unterminated UTF-8 sequence when encoding string
[2020-04-21 11:15:07,430] [ERROR] [buffer.py] [87] - json.dumps:Unterminated UTF-8 sequence when encoding string
Traceback (most recent call last):
  File "C:\Users\lenovo\Desktop\spider\data_buffer\buffer.py", line 82, in pushall
    dest_data = json.dumps(data)
OverflowError: Unterminated UTF-8 sequence when encoding string
[2020-04-23 16:25:04,747] [ERROR] [buffer.py] [87] - json.dumps:Unterminated UTF-8 sequence when encoding string
Traceback (most recent call last):
  File "C:\Users\lenovo\Desktop\spider\data_buffer\buffer.py", line 82, in pushall
    dest_data = json.dumps(data)
OverflowError: Unterminated UTF-8 sequence when encoding string
[2020-04-23 16:36:12,210] [ERROR] [buffer.py] [87] - json.dumps:Unterminated UTF-8 sequence when encoding string
Traceback (most recent call last):
  File "C:\Users\lenovo\Desktop\spider\data_buffer\buffer.py", line 82, in pushall
    dest_data = json.dumps(data)
OverflowError: Unterminated UTF-8 sequence when encoding string
[2020-04-23 16:36:15,022] [ERROR] [buffer.py] [87] - json.dumps:Unsupported UTF-8 sequence length when encoding string
Traceback (most recent call last):
  File "C:\Users\lenovo\Desktop\spider\data_buffer\buffer.py", line 82, in pushall
    dest_data = json.dumps(data)
OverflowError: Unsupported UTF-8 sequence length when encoding string
[2020-04-23 16:36:20,354] [ERROR] [buffer.py] [87] - json.dumps:Unterminated UTF-8 sequence when encoding string
Traceback (most recent call last):
  File "C:\Users\lenovo\Desktop\spider\data_buffer\buffer.py", line 82, in pushall
    dest_data = json.dumps(data)
OverflowError: Unterminated UTF-8 sequence when encoding string
[2020-05-21 16:38:13,835] [ERROR] [buffer.py] [87] - json.dumps:'utf8' codec can't decode byte 0xa1 in position 0: invalid start byte
Traceback (most recent call last):
  File "D:\spider\data_buffer\buffer.py", line 82, in pushall
    dest_data = json.dumps(data)
  File "D:\Anaconda2\Lib\json\__init__.py", line 244, in dumps
    return _default_encoder.encode(obj)
  File "D:\Anaconda2\Lib\json\encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "D:\Anaconda2\Lib\json\encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xa1 in position 0: invalid start byte
[2020-07-21 09:35:21,095] [ERROR] [buffer.py] [112] - buffer redis pop exception: invalid literal for int() with base 10: '192.168.2.122', src_data=''
Traceback (most recent call last):
  File "F:/spider/data_buffer/buffer.py", line 108, in pop
    src_data = self.conn.lpop(self.key_name)
  File "C:\Python27\lib\site-packages\redis\client.py", line 1957, in lpop
    return self.execute_command('LPOP', name)
  File "C:\Python27\lib\site-packages\redis\client.py", line 898, in execute_command
    conn = self.connection or pool.get_connection(command_name, **options)
  File "C:\Python27\lib\site-packages\redis\connection.py", line 1187, in get_connection
    connection = self.make_connection()
  File "C:\Python27\lib\site-packages\redis\connection.py", line 1227, in make_connection
    return self.connection_class(**self.connection_kwargs)
  File "C:\Python27\lib\site-packages\redis\connection.py", line 509, in __init__
    self.port = int(port)
ValueError: invalid literal for int() with base 10: '192.168.2.122'
[2020-08-10 20:03:26,148] [ERROR] [buffer.py] [87] - json.dumps:<htmlparser.Parser object at 0x05758FF0> is not JSON serializable
Traceback (most recent call last):
  File "F:\spider\data_buffer\buffer.py", line 82, in pushall
    dest_data = json.dumps(data)
  File "C:\Python27\Lib\json\__init__.py", line 244, in dumps
    return _default_encoder.encode(obj)
  File "C:\Python27\Lib\json\encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Python27\Lib\json\encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
  File "C:\Python27\Lib\json\encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: <htmlparser.Parser object at 0x05758FF0> is not JSON serializable
[2020-08-10 20:03:26,631] [ERROR] [buffer.py] [87] - json.dumps:<htmlparser.Parser object at 0x05760710> is not JSON serializable
Traceback (most recent call last):
  File "F:\spider\data_buffer\buffer.py", line 82, in pushall
    dest_data = json.dumps(data)
  File "C:\Python27\Lib\json\__init__.py", line 244, in dumps
    return _default_encoder.encode(obj)
  File "C:\Python27\Lib\json\encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Python27\Lib\json\encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
  File "C:\Python27\Lib\json\encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: <htmlparser.Parser object at 0x05760710> is not JSON serializable
[2020-08-10 20:03:26,872] [ERROR] [buffer.py] [87] - json.dumps:<htmlparser.Parser object at 0x055153D0> is not JSON serializable
Traceback (most recent call last):
  File "F:\spider\data_buffer\buffer.py", line 82, in pushall
    dest_data = json.dumps(data)
  File "C:\Python27\Lib\json\__init__.py", line 244, in dumps
    return _default_encoder.encode(obj)
  File "C:\Python27\Lib\json\encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Python27\Lib\json\encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
  File "C:\Python27\Lib\json\encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: <htmlparser.Parser object at 0x055153D0> is not JSON serializable
[2020-08-10 20:03:27,086] [ERROR] [buffer.py] [87] - json.dumps:<htmlparser.Parser object at 0x057826B0> is not JSON serializable
Traceback (most recent call last):
  File "F:\spider\data_buffer\buffer.py", line 82, in pushall
    dest_data = json.dumps(data)
  File "C:\Python27\Lib\json\__init__.py", line 244, in dumps
    return _default_encoder.encode(obj)
  File "C:\Python27\Lib\json\encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Python27\Lib\json\encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
  File "C:\Python27\Lib\json\encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: <htmlparser.Parser object at 0x057826B0> is not JSON serializable
[2020-08-10 20:03:27,295] [ERROR] [buffer.py] [87] - json.dumps:<htmlparser.Parser object at 0x0577ABD0> is not JSON serializable
Traceback (most recent call last):
  File "F:\spider\data_buffer\buffer.py", line 82, in pushall
    dest_data = json.dumps(data)
  File "C:\Python27\Lib\json\__init__.py", line 244, in dumps
    return _default_encoder.encode(obj)
  File "C:\Python27\Lib\json\encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Python27\Lib\json\encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
  File "C:\Python27\Lib\json\encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: <htmlparser.Parser object at 0x0577ABD0> is not JSON serializable
[2020-08-10 20:03:27,997] [ERROR] [buffer.py] [87] - json.dumps:<htmlparser.Parser object at 0x05515CB0> is not JSON serializable
Traceback (most recent call last):
  File "F:\spider\data_buffer\buffer.py", line 82, in pushall
    dest_data = json.dumps(data)
  File "C:\Python27\Lib\json\__init__.py", line 244, in dumps
    return _default_encoder.encode(obj)
  File "C:\Python27\Lib\json\encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Python27\Lib\json\encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
  File "C:\Python27\Lib\json\encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: <htmlparser.Parser object at 0x05515CB0> is not JSON serializable
[2020-08-10 20:03:28,351] [ERROR] [buffer.py] [87] - json.dumps:<htmlparser.Parser object at 0x05ECFB10> is not JSON serializable
Traceback (most recent call last):
  File "F:\spider\data_buffer\buffer.py", line 82, in pushall
    dest_data = json.dumps(data)
  File "C:\Python27\Lib\json\__init__.py", line 244, in dumps
    return _default_encoder.encode(obj)
  File "C:\Python27\Lib\json\encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Python27\Lib\json\encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
  File "C:\Python27\Lib\json\encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: <htmlparser.Parser object at 0x05ECFB10> is not JSON serializable
[2020-08-10 20:03:28,555] [ERROR] [buffer.py] [87] - json.dumps:<htmlparser.Parser object at 0x047FFA90> is not JSON serializable
Traceback (most recent call last):
  File "F:\spider\data_buffer\buffer.py", line 82, in pushall
    dest_data = json.dumps(data)
  File "C:\Python27\Lib\json\__init__.py", line 244, in dumps
    return _default_encoder.encode(obj)
  File "C:\Python27\Lib\json\encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Python27\Lib\json\encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
  File "C:\Python27\Lib\json\encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: <htmlparser.Parser object at 0x047FFA90> is not JSON serializable
[2020-08-10 20:03:28,770] [ERROR] [buffer.py] [87] - json.dumps:<htmlparser.Parser object at 0x05758170> is not JSON serializable
Traceback (most recent call last):
  File "F:\spider\data_buffer\buffer.py", line 82, in pushall
    dest_data = json.dumps(data)
  File "C:\Python27\Lib\json\__init__.py", line 244, in dumps
    return _default_encoder.encode(obj)
  File "C:\Python27\Lib\json\encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Python27\Lib\json\encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
  File "C:\Python27\Lib\json\encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: <htmlparser.Parser object at 0x05758170> is not JSON serializable
[2020-08-10 20:03:29,002] [ERROR] [buffer.py] [87] - json.dumps:<htmlparser.Parser object at 0x05515EB0> is not JSON serializable
Traceback (most recent call last):
  File "F:\spider\data_buffer\buffer.py", line 82, in pushall
    dest_data = json.dumps(data)
  File "C:\Python27\Lib\json\__init__.py", line 244, in dumps
    return _default_encoder.encode(obj)
  File "C:\Python27\Lib\json\encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Python27\Lib\json\encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
  File "C:\Python27\Lib\json\encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: <htmlparser.Parser object at 0x05515EB0> is not JSON serializable
[2020-08-10 20:03:30,530] [ERROR] [buffer.py] [87] - json.dumps:<htmlparser.Parser object at 0x055B9B70> is not JSON serializable
Traceback (most recent call last):
  File "F:\spider\data_buffer\buffer.py", line 82, in pushall
    dest_data = json.dumps(data)
  File "C:\Python27\Lib\json\__init__.py", line 244, in dumps
    return _default_encoder.encode(obj)
  File "C:\Python27\Lib\json\encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Python27\Lib\json\encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
  File "C:\Python27\Lib\json\encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: <htmlparser.Parser object at 0x055B9B70> is not JSON serializable
[2020-08-10 20:03:30,772] [ERROR] [buffer.py] [87] - json.dumps:<htmlparser.Parser object at 0x05782C30> is not JSON serializable
Traceback (most recent call last):
  File "F:\spider\data_buffer\buffer.py", line 82, in pushall
    dest_data = json.dumps(data)
  File "C:\Python27\Lib\json\__init__.py", line 244, in dumps
    return _default_encoder.encode(obj)
  File "C:\Python27\Lib\json\encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Python27\Lib\json\encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
  File "C:\Python27\Lib\json\encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: <htmlparser.Parser object at 0x05782C30> is not JSON serializable
[2020-08-10 20:03:30,924] [ERROR] [buffer.py] [87] - json.dumps:<htmlparser.Parser object at 0x046AB490> is not JSON serializable
Traceback (most recent call last):
  File "F:\spider\data_buffer\buffer.py", line 82, in pushall
    dest_data = json.dumps(data)
  File "C:\Python27\Lib\json\__init__.py", line 244, in dumps
    return _default_encoder.encode(obj)
  File "C:\Python27\Lib\json\encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Python27\Lib\json\encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
  File "C:\Python27\Lib\json\encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: <htmlparser.Parser object at 0x046AB490> is not JSON serializable
[2020-08-10 20:03:31,105] [ERROR] [buffer.py] [87] - json.dumps:<htmlparser.Parser object at 0x055B91B0> is not JSON serializable
Traceback (most recent call last):
  File "F:\spider\data_buffer\buffer.py", line 82, in pushall
    dest_data = json.dumps(data)
  File "C:\Python27\Lib\json\__init__.py", line 244, in dumps
    return _default_encoder.encode(obj)
  File "C:\Python27\Lib\json\encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Python27\Lib\json\encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
  File "C:\Python27\Lib\json\encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: <htmlparser.Parser object at 0x055B91B0> is not JSON serializable
[2020-08-10 20:03:31,467] [ERROR] [buffer.py] [87] - json.dumps:<htmlparser.Parser object at 0x05ECF390> is not JSON serializable
Traceback (most recent call last):
  File "F:\spider\data_buffer\buffer.py", line 82, in pushall
    dest_data = json.dumps(data)
  File "C:\Python27\Lib\json\__init__.py", line 244, in dumps
    return _default_encoder.encode(obj)
  File "C:\Python27\Lib\json\encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Python27\Lib\json\encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
  File "C:\Python27\Lib\json\encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: <htmlparser.Parser object at 0x05ECF390> is not JSON serializable
[2020-08-10 20:03:31,765] [ERROR] [buffer.py] [87] - json.dumps:<htmlparser.Parser object at 0x05760650> is not JSON serializable
Traceback (most recent call last):
  File "F:\spider\data_buffer\buffer.py", line 82, in pushall
    dest_data = json.dumps(data)
  File "C:\Python27\Lib\json\__init__.py", line 244, in dumps
    return _default_encoder.encode(obj)
  File "C:\Python27\Lib\json\encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Python27\Lib\json\encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
  File "C:\Python27\Lib\json\encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: <htmlparser.Parser object at 0x05760650> is not JSON serializable
[2020-08-10 20:03:31,790] [ERROR] [buffer.py] [87] - json.dumps:<htmlparser.Parser object at 0x057587B0> is not JSON serializable
Traceback (most recent call last):
  File "F:\spider\data_buffer\buffer.py", line 82, in pushall
    dest_data = json.dumps(data)
  File "C:\Python27\Lib\json\__init__.py", line 244, in dumps
    return _default_encoder.encode(obj)
  File "C:\Python27\Lib\json\encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Python27\Lib\json\encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
  File "C:\Python27\Lib\json\encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: <htmlparser.Parser object at 0x057587B0> is not JSON serializable
[2020-08-10 20:03:31,861] [ERROR] [buffer.py] [87] - json.dumps:<htmlparser.Parser object at 0x042D6DF0> is not JSON serializable
Traceback (most recent call last):
  File "F:\spider\data_buffer\buffer.py", line 82, in pushall
    dest_data = json.dumps(data)
  File "C:\Python27\Lib\json\__init__.py", line 244, in dumps
    return _default_encoder.encode(obj)
  File "C:\Python27\Lib\json\encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Python27\Lib\json\encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
  File "C:\Python27\Lib\json\encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: <htmlparser.Parser object at 0x042D6DF0> is not JSON serializable
[2020-08-10 20:03:31,921] [ERROR] [buffer.py] [87] - json.dumps:<htmlparser.Parser object at 0x0576AD70> is not JSON serializable
Traceback (most recent call last):
  File "F:\spider\data_buffer\buffer.py", line 82, in pushall
    dest_data = json.dumps(data)
  File "C:\Python27\Lib\json\__init__.py", line 244, in dumps
    return _default_encoder.encode(obj)
  File "C:\Python27\Lib\json\encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Python27\Lib\json\encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
  File "C:\Python27\Lib\json\encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: <htmlparser.Parser object at 0x0576AD70> is not JSON serializable
[2020-08-10 20:03:32,358] [ERROR] [buffer.py] [87] - json.dumps:<htmlparser.Parser object at 0x055B9970> is not JSON serializable
Traceback (most recent call last):
  File "F:\spider\data_buffer\buffer.py", line 82, in pushall
    dest_data = json.dumps(data)
  File "C:\Python27\Lib\json\__init__.py", line 244, in dumps
    return _default_encoder.encode(obj)
  File "C:\Python27\Lib\json\encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Python27\Lib\json\encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
  File "C:\Python27\Lib\json\encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: <htmlparser.Parser object at 0x055B9970> is not JSON serializable
[2020-08-10 20:03:33,730] [ERROR] [buffer.py] [87] - json.dumps:<htmlparser.Parser object at 0x055153B0> is not JSON serializable
Traceback (most recent call last):
  File "F:\spider\data_buffer\buffer.py", line 82, in pushall
    dest_data = json.dumps(data)
  File "C:\Python27\Lib\json\__init__.py", line 244, in dumps
    return _default_encoder.encode(obj)
  File "C:\Python27\Lib\json\encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Python27\Lib\json\encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
  File "C:\Python27\Lib\json\encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: <htmlparser.Parser object at 0x055153B0> is not JSON serializable
[2020-08-10 20:03:33,970] [ERROR] [buffer.py] [87] - json.dumps:<htmlparser.Parser object at 0x055153D0> is not JSON serializable
Traceback (most recent call last):
  File "F:\spider\data_buffer\buffer.py", line 82, in pushall
    dest_data = json.dumps(data)
  File "C:\Python27\Lib\json\__init__.py", line 244, in dumps
    return _default_encoder.encode(obj)
  File "C:\Python27\Lib\json\encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Python27\Lib\json\encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
  File "C:\Python27\Lib\json\encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: <htmlparser.Parser object at 0x055153D0> is not JSON serializable
[2020-08-10 20:03:34,062] [ERROR] [buffer.py] [87] - json.dumps:<htmlparser.Parser object at 0x047F5DF0> is not JSON serializable
Traceback (most recent call last):
  File "F:\spider\data_buffer\buffer.py", line 82, in pushall
    dest_data = json.dumps(data)
  File "C:\Python27\Lib\json\__init__.py", line 244, in dumps
    return _default_encoder.encode(obj)
  File "C:\Python27\Lib\json\encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Python27\Lib\json\encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
  File "C:\Python27\Lib\json\encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: <htmlparser.Parser object at 0x047F5DF0> is not JSON serializable
[2020-08-10 20:03:34,259] [ERROR] [buffer.py] [87] - json.dumps:<htmlparser.Parser object at 0x05515EB0> is not JSON serializable
Traceback (most recent call last):
  File "F:\spider\data_buffer\buffer.py", line 82, in pushall
    dest_data = json.dumps(data)
  File "C:\Python27\Lib\json\__init__.py", line 244, in dumps
    return _default_encoder.encode(obj)
  File "C:\Python27\Lib\json\encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Python27\Lib\json\encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
  File "C:\Python27\Lib\json\encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: <htmlparser.Parser object at 0x05515EB0> is not JSON serializable
[2020-08-10 20:03:34,479] [ERROR] [buffer.py] [87] - json.dumps:<htmlparser.Parser object at 0x0576ADF0> is not JSON serializable
Traceback (most recent call last):
  File "F:\spider\data_buffer\buffer.py", line 82, in pushall
    dest_data = json.dumps(data)
  File "C:\Python27\Lib\json\__init__.py", line 244, in dumps
    return _default_encoder.encode(obj)
  File "C:\Python27\Lib\json\encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Python27\Lib\json\encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
  File "C:\Python27\Lib\json\encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: <htmlparser.Parser object at 0x0576ADF0> is not JSON serializable
[2020-08-10 20:03:35,072] [ERROR] [buffer.py] [87] - json.dumps:<htmlparser.Parser object at 0x05ECC690> is not JSON serializable
Traceback (most recent call last):
  File "F:\spider\data_buffer\buffer.py", line 82, in pushall
    dest_data = json.dumps(data)
  File "C:\Python27\Lib\json\__init__.py", line 244, in dumps
    return _default_encoder.encode(obj)
  File "C:\Python27\Lib\json\encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Python27\Lib\json\encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
  File "C:\Python27\Lib\json\encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: <htmlparser.Parser object at 0x05ECC690> is not JSON serializable
[2020-08-10 20:03:35,115] [ERROR] [buffer.py] [87] - json.dumps:<htmlparser.Parser object at 0x057585D0> is not JSON serializable
Traceback (most recent call last):
  File "F:\spider\data_buffer\buffer.py", line 82, in pushall
    dest_data = json.dumps(data)
  File "C:\Python27\Lib\json\__init__.py", line 244, in dumps
    return _default_encoder.encode(obj)
  File "C:\Python27\Lib\json\encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Python27\Lib\json\encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
  File "C:\Python27\Lib\json\encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: <htmlparser.Parser object at 0x057585D0> is not JSON serializable
[2020-08-10 20:03:35,157] [ERROR] [buffer.py] [87] - json.dumps:<htmlparser.Parser object at 0x05ECFB30> is not JSON serializable
Traceback (most recent call last):
  File "F:\spider\data_buffer\buffer.py", line 82, in pushall
    dest_data = json.dumps(data)
  File "C:\Python27\Lib\json\__init__.py", line 244, in dumps
    return _default_encoder.encode(obj)
  File "C:\Python27\Lib\json\encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Python27\Lib\json\encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
  File "C:\Python27\Lib\json\encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: <htmlparser.Parser object at 0x05ECFB30> is not JSON serializable
[2020-08-10 20:03:35,368] [ERROR] [buffer.py] [87] - json.dumps:<htmlparser.Parser object at 0x05ECF870> is not JSON serializable
Traceback (most recent call last):
  File "F:\spider\data_buffer\buffer.py", line 82, in pushall
    dest_data = json.dumps(data)
  File "C:\Python27\Lib\json\__init__.py", line 244, in dumps
    return _default_encoder.encode(obj)
  File "C:\Python27\Lib\json\encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Python27\Lib\json\encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
  File "C:\Python27\Lib\json\encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: <htmlparser.Parser object at 0x05ECF870> is not JSON serializable
[2020-08-10 20:03:35,586] [ERROR] [buffer.py] [87] - json.dumps:<htmlparser.Parser object at 0x055B9290> is not JSON serializable
Traceback (most recent call last):
  File "F:\spider\data_buffer\buffer.py", line 82, in pushall
    dest_data = json.dumps(data)
  File "C:\Python27\Lib\json\__init__.py", line 244, in dumps
    return _default_encoder.encode(obj)
  File "C:\Python27\Lib\json\encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Python27\Lib\json\encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
  File "C:\Python27\Lib\json\encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: <htmlparser.Parser object at 0x055B9290> is not JSON serializable
[2020-08-10 20:03:36,950] [ERROR] [buffer.py] [87] - json.dumps:<htmlparser.Parser object at 0x047E9110> is not JSON serializable
Traceback (most recent call last):
  File "F:\spider\data_buffer\buffer.py", line 82, in pushall
    dest_data = json.dumps(data)
  File "C:\Python27\Lib\json\__init__.py", line 244, in dumps
    return _default_encoder.encode(obj)
  File "C:\Python27\Lib\json\encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Python27\Lib\json\encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
  File "C:\Python27\Lib\json\encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: <htmlparser.Parser object at 0x047E9110> is not JSON serializable
[2020-08-10 20:03:37,112] [ERROR] [buffer.py] [87] - json.dumps:<htmlparser.Parser object at 0x047F5CD0> is not JSON serializable
Traceback (most recent call last):
  File "F:\spider\data_buffer\buffer.py", line 82, in pushall
    dest_data = json.dumps(data)
  File "C:\Python27\Lib\json\__init__.py", line 244, in dumps
    return _default_encoder.encode(obj)
  File "C:\Python27\Lib\json\encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Python27\Lib\json\encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
  File "C:\Python27\Lib\json\encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: <htmlparser.Parser object at 0x047F5CD0> is not JSON serializable
[2020-08-10 20:03:37,311] [ERROR] [buffer.py] [87] - json.dumps:<htmlparser.Parser object at 0x057585D0> is not JSON serializable
Traceback (most recent call last):
  File "F:\spider\data_buffer\buffer.py", line 82, in pushall
    dest_data = json.dumps(data)
  File "C:\Python27\Lib\json\__init__.py", line 244, in dumps
    return _default_encoder.encode(obj)
  File "C:\Python27\Lib\json\encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Python27\Lib\json\encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
  File "C:\Python27\Lib\json\encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: <htmlparser.Parser object at 0x057585D0> is not JSON serializable
[2020-08-10 20:03:37,503] [ERROR] [buffer.py] [87] - json.dumps:<htmlparser.Parser object at 0x05ECFF30> is not JSON serializable
Traceback (most recent call last):
  File "F:\spider\data_buffer\buffer.py", line 82, in pushall
    dest_data = json.dumps(data)
  File "C:\Python27\Lib\json\__init__.py", line 244, in dumps
    return _default_encoder.encode(obj)
  File "C:\Python27\Lib\json\encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Python27\Lib\json\encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
  File "C:\Python27\Lib\json\encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: <htmlparser.Parser object at 0x05ECFF30> is not JSON serializable
[2020-08-10 20:03:37,700] [ERROR] [buffer.py] [87] - json.dumps:<htmlparser.Parser object at 0x055B9810> is not JSON serializable
Traceback (most recent call last):
  File "F:\spider\data_buffer\buffer.py", line 82, in pushall
    dest_data = json.dumps(data)
  File "C:\Python27\Lib\json\__init__.py", line 244, in dumps
    return _default_encoder.encode(obj)
  File "C:\Python27\Lib\json\encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Python27\Lib\json\encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
  File "C:\Python27\Lib\json\encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: <htmlparser.Parser object at 0x055B9810> is not JSON serializable
[2020-08-10 20:03:39,226] [ERROR] [buffer.py] [87] - json.dumps:<htmlparser.Parser object at 0x05ECC350> is not JSON serializable
Traceback (most recent call last):
  File "F:\spider\data_buffer\buffer.py", line 82, in pushall
    dest_data = json.dumps(data)
  File "C:\Python27\Lib\json\__init__.py", line 244, in dumps
    return _default_encoder.encode(obj)
  File "C:\Python27\Lib\json\encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Python27\Lib\json\encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
  File "C:\Python27\Lib\json\encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: <htmlparser.Parser object at 0x05ECC350> is not JSON serializable
[2020-08-10 20:03:39,535] [ERROR] [buffer.py] [87] - json.dumps:<htmlparser.Parser object at 0x05ECFAF0> is not JSON serializable
Traceback (most recent call last):
  File "F:\spider\data_buffer\buffer.py", line 82, in pushall
    dest_data = json.dumps(data)
  File "C:\Python27\Lib\json\__init__.py", line 244, in dumps
    return _default_encoder.encode(obj)
  File "C:\Python27\Lib\json\encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Python27\Lib\json\encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
  File "C:\Python27\Lib\json\encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: <htmlparser.Parser object at 0x05ECFAF0> is not JSON serializable
[2020-08-10 20:03:39,836] [ERROR] [buffer.py] [87] - json.dumps:<htmlparser.Parser object at 0x05515ED0> is not JSON serializable
Traceback (most recent call last):
  File "F:\spider\data_buffer\buffer.py", line 82, in pushall
    dest_data = json.dumps(data)
  File "C:\Python27\Lib\json\__init__.py", line 244, in dumps
    return _default_encoder.encode(obj)
  File "C:\Python27\Lib\json\encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Python27\Lib\json\encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
  File "C:\Python27\Lib\json\encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: <htmlparser.Parser object at 0x05515ED0> is not JSON serializable
[2020-08-10 20:03:39,977] [ERROR] [buffer.py] [87] - json.dumps:<htmlparser.Parser object at 0x046AB1F0> is not JSON serializable
Traceback (most recent call last):
  File "F:\spider\data_buffer\buffer.py", line 82, in pushall
    dest_data = json.dumps(data)
  File "C:\Python27\Lib\json\__init__.py", line 244, in dumps
    return _default_encoder.encode(obj)
  File "C:\Python27\Lib\json\encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Python27\Lib\json\encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
  File "C:\Python27\Lib\json\encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: <htmlparser.Parser object at 0x046AB1F0> is not JSON serializable
[2020-08-10 20:03:40,190] [ERROR] [buffer.py] [87] - json.dumps:<htmlparser.Parser object at 0x055B98F0> is not JSON serializable
Traceback (most recent call last):
  File "F:\spider\data_buffer\buffer.py", line 82, in pushall
    dest_data = json.dumps(data)
  File "C:\Python27\Lib\json\__init__.py", line 244, in dumps
    return _default_encoder.encode(obj)
  File "C:\Python27\Lib\json\encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Python27\Lib\json\encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
  File "C:\Python27\Lib\json\encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: <htmlparser.Parser object at 0x055B98F0> is not JSON serializable
[2020-08-10 20:03:41,599] [ERROR] [buffer.py] [87] - json.dumps:<htmlparser.Parser object at 0x05EDFF50> is not JSON serializable
Traceback (most recent call last):
  File "F:\spider\data_buffer\buffer.py", line 82, in pushall
    dest_data = json.dumps(data)
  File "C:\Python27\Lib\json\__init__.py", line 244, in dumps
    return _default_encoder.encode(obj)
  File "C:\Python27\Lib\json\encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Python27\Lib\json\encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
  File "C:\Python27\Lib\json\encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: <htmlparser.Parser object at 0x05EDFF50> is not JSON serializable
[2020-08-10 20:03:41,653] [ERROR] [buffer.py] [87] - json.dumps:<htmlparser.Parser object at 0x05ECF630> is not JSON serializable
Traceback (most recent call last):
  File "F:\spider\data_buffer\buffer.py", line 82, in pushall
    dest_data = json.dumps(data)
  File "C:\Python27\Lib\json\__init__.py", line 244, in dumps
    return _default_encoder.encode(obj)
  File "C:\Python27\Lib\json\encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Python27\Lib\json\encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
  File "C:\Python27\Lib\json\encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: <htmlparser.Parser object at 0x05ECF630> is not JSON serializable
[2020-08-10 20:03:41,746] [ERROR] [buffer.py] [87] - json.dumps:<htmlparser.Parser object at 0x0577A650> is not JSON serializable
Traceback (most recent call last):
  File "F:\spider\data_buffer\buffer.py", line 82, in pushall
    dest_data = json.dumps(data)
  File "C:\Python27\Lib\json\__init__.py", line 244, in dumps
    return _default_encoder.encode(obj)
  File "C:\Python27\Lib\json\encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Python27\Lib\json\encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
  File "C:\Python27\Lib\json\encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: <htmlparser.Parser object at 0x0577A650> is not JSON serializable
[2020-08-10 20:03:41,994] [ERROR] [buffer.py] [87] - json.dumps:<htmlparser.Parser object at 0x055B9210> is not JSON serializable
Traceback (most recent call last):
  File "F:\spider\data_buffer\buffer.py", line 82, in pushall
    dest_data = json.dumps(data)
  File "C:\Python27\Lib\json\__init__.py", line 244, in dumps
    return _default_encoder.encode(obj)
  File "C:\Python27\Lib\json\encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Python27\Lib\json\encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
  File "C:\Python27\Lib\json\encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: <htmlparser.Parser object at 0x055B9210> is not JSON serializable
[2020-08-10 20:03:42,072] [ERROR] [buffer.py] [87] - json.dumps:<htmlparser.Parser object at 0x05515E10> is not JSON serializable
Traceback (most recent call last):
  File "F:\spider\data_buffer\buffer.py", line 82, in pushall
    dest_data = json.dumps(data)
  File "C:\Python27\Lib\json\__init__.py", line 244, in dumps
    return _default_encoder.encode(obj)
  File "C:\Python27\Lib\json\encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Python27\Lib\json\encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
  File "C:\Python27\Lib\json\encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: <htmlparser.Parser object at 0x05515E10> is not JSON serializable
[2020-08-10 20:03:43,059] [ERROR] [buffer.py] [87] - json.dumps:<htmlparser.Parser object at 0x047FF8F0> is not JSON serializable
Traceback (most recent call last):
  File "F:\spider\data_buffer\buffer.py", line 82, in pushall
    dest_data = json.dumps(data)
  File "C:\Python27\Lib\json\__init__.py", line 244, in dumps
    return _default_encoder.encode(obj)
  File "C:\Python27\Lib\json\encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Python27\Lib\json\encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
  File "C:\Python27\Lib\json\encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: <htmlparser.Parser object at 0x047FF8F0> is not JSON serializable
[2020-08-10 20:03:43,108] [ERROR] [buffer.py] [87] - json.dumps:<htmlparser.Parser object at 0x047FF830> is not JSON serializable
Traceback (most recent call last):
  File "F:\spider\data_buffer\buffer.py", line 82, in pushall
    dest_data = json.dumps(data)
  File "C:\Python27\Lib\json\__init__.py", line 244, in dumps
    return _default_encoder.encode(obj)
  File "C:\Python27\Lib\json\encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Python27\Lib\json\encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
  File "C:\Python27\Lib\json\encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: <htmlparser.Parser object at 0x047FF830> is not JSON serializable
[2020-08-10 20:03:43,167] [ERROR] [buffer.py] [87] - json.dumps:<htmlparser.Parser object at 0x05ECC910> is not JSON serializable
Traceback (most recent call last):
  File "F:\spider\data_buffer\buffer.py", line 82, in pushall
    dest_data = json.dumps(data)
  File "C:\Python27\Lib\json\__init__.py", line 244, in dumps
    return _default_encoder.encode(obj)
  File "C:\Python27\Lib\json\encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Python27\Lib\json\encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
  File "C:\Python27\Lib\json\encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: <htmlparser.Parser object at 0x05ECC910> is not JSON serializable
[2020-08-10 20:03:43,221] [ERROR] [buffer.py] [87] - json.dumps:<htmlparser.Parser object at 0x05ECC090> is not JSON serializable
Traceback (most recent call last):
  File "F:\spider\data_buffer\buffer.py", line 82, in pushall
    dest_data = json.dumps(data)
  File "C:\Python27\Lib\json\__init__.py", line 244, in dumps
    return _default_encoder.encode(obj)
  File "C:\Python27\Lib\json\encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Python27\Lib\json\encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
  File "C:\Python27\Lib\json\encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: <htmlparser.Parser object at 0x05ECC090> is not JSON serializable
[2020-08-10 20:03:43,487] [ERROR] [buffer.py] [87] - json.dumps:<htmlparser.Parser object at 0x046AB490> is not JSON serializable
Traceback (most recent call last):
  File "F:\spider\data_buffer\buffer.py", line 82, in pushall
    dest_data = json.dumps(data)
  File "C:\Python27\Lib\json\__init__.py", line 244, in dumps
    return _default_encoder.encode(obj)
  File "C:\Python27\Lib\json\encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Python27\Lib\json\encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
  File "C:\Python27\Lib\json\encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: <htmlparser.Parser object at 0x046AB490> is not JSON serializable
[2020-08-10 20:03:44,941] [ERROR] [buffer.py] [87] - json.dumps:<htmlparser.Parser object at 0x047E9070> is not JSON serializable
Traceback (most recent call last):
  File "F:\spider\data_buffer\buffer.py", line 82, in pushall
    dest_data = json.dumps(data)
  File "C:\Python27\Lib\json\__init__.py", line 244, in dumps
    return _default_encoder.encode(obj)
  File "C:\Python27\Lib\json\encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Python27\Lib\json\encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
  File "C:\Python27\Lib\json\encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: <htmlparser.Parser object at 0x047E9070> is not JSON serializable
[2020-08-10 20:03:44,993] [ERROR] [buffer.py] [87] - json.dumps:<htmlparser.Parser object at 0x046AB490> is not JSON serializable
Traceback (most recent call last):
  File "F:\spider\data_buffer\buffer.py", line 82, in pushall
    dest_data = json.dumps(data)
  File "C:\Python27\Lib\json\__init__.py", line 244, in dumps
    return _default_encoder.encode(obj)
  File "C:\Python27\Lib\json\encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Python27\Lib\json\encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
  File "C:\Python27\Lib\json\encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: <htmlparser.Parser object at 0x046AB490> is not JSON serializable
[2020-08-10 20:03:45,109] [ERROR] [buffer.py] [87] - json.dumps:<htmlparser.Parser object at 0x046AB130> is not JSON serializable
Traceback (most recent call last):
  File "F:\spider\data_buffer\buffer.py", line 82, in pushall
    dest_data = json.dumps(data)
  File "C:\Python27\Lib\json\__init__.py", line 244, in dumps
    return _default_encoder.encode(obj)
  File "C:\Python27\Lib\json\encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Python27\Lib\json\encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
  File "C:\Python27\Lib\json\encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: <htmlparser.Parser object at 0x046AB130> is not JSON serializable
[2020-08-10 20:03:45,338] [ERROR] [buffer.py] [87] - json.dumps:<htmlparser.Parser object at 0x046AB490> is not JSON serializable
Traceback (most recent call last):
  File "F:\spider\data_buffer\buffer.py", line 82, in pushall
    dest_data = json.dumps(data)
  File "C:\Python27\Lib\json\__init__.py", line 244, in dumps
    return _default_encoder.encode(obj)
  File "C:\Python27\Lib\json\encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Python27\Lib\json\encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
  File "C:\Python27\Lib\json\encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: <htmlparser.Parser object at 0x046AB490> is not JSON serializable
[2020-08-10 20:03:45,529] [ERROR] [buffer.py] [87] - json.dumps:<htmlparser.Parser object at 0x05ECC7B0> is not JSON serializable
Traceback (most recent call last):
  File "F:\spider\data_buffer\buffer.py", line 82, in pushall
    dest_data = json.dumps(data)
  File "C:\Python27\Lib\json\__init__.py", line 244, in dumps
    return _default_encoder.encode(obj)
  File "C:\Python27\Lib\json\encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Python27\Lib\json\encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
  File "C:\Python27\Lib\json\encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: <htmlparser.Parser object at 0x05ECC7B0> is not JSON serializable
[2020-08-10 20:03:47,020] [ERROR] [buffer.py] [87] - json.dumps:<htmlparser.Parser object at 0x05EDF0B0> is not JSON serializable
Traceback (most recent call last):
  File "F:\spider\data_buffer\buffer.py", line 82, in pushall
    dest_data = json.dumps(data)
  File "C:\Python27\Lib\json\__init__.py", line 244, in dumps
    return _default_encoder.encode(obj)
  File "C:\Python27\Lib\json\encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Python27\Lib\json\encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
  File "C:\Python27\Lib\json\encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: <htmlparser.Parser object at 0x05EDF0B0> is not JSON serializable
[2020-08-10 20:03:47,293] [ERROR] [buffer.py] [87] - json.dumps:<htmlparser.Parser object at 0x05EDF550> is not JSON serializable
Traceback (most recent call last):
  File "F:\spider\data_buffer\buffer.py", line 82, in pushall
    dest_data = json.dumps(data)
  File "C:\Python27\Lib\json\__init__.py", line 244, in dumps
    return _default_encoder.encode(obj)
  File "C:\Python27\Lib\json\encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Python27\Lib\json\encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
  File "C:\Python27\Lib\json\encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: <htmlparser.Parser object at 0x05EDF550> is not JSON serializable
[2020-08-10 20:03:47,516] [ERROR] [buffer.py] [87] - json.dumps:<htmlparser.Parser object at 0x05ECF430> is not JSON serializable
Traceback (most recent call last):
  File "F:\spider\data_buffer\buffer.py", line 82, in pushall
    dest_data = json.dumps(data)
  File "C:\Python27\Lib\json\__init__.py", line 244, in dumps
    return _default_encoder.encode(obj)
  File "C:\Python27\Lib\json\encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Python27\Lib\json\encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
  File "C:\Python27\Lib\json\encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: <htmlparser.Parser object at 0x05ECF430> is not JSON serializable
[2020-08-10 20:03:47,749] [ERROR] [buffer.py] [87] - json.dumps:<htmlparser.Parser object at 0x047F5F50> is not JSON serializable
Traceback (most recent call last):
  File "F:\spider\data_buffer\buffer.py", line 82, in pushall
    dest_data = json.dumps(data)
  File "C:\Python27\Lib\json\__init__.py", line 244, in dumps
    return _default_encoder.encode(obj)
  File "C:\Python27\Lib\json\encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Python27\Lib\json\encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
  File "C:\Python27\Lib\json\encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: <htmlparser.Parser object at 0x047F5F50> is not JSON serializable
[2020-08-10 20:03:47,971] [ERROR] [buffer.py] [87] - json.dumps:<htmlparser.Parser object at 0x05ECF930> is not JSON serializable
Traceback (most recent call last):
  File "F:\spider\data_buffer\buffer.py", line 82, in pushall
    dest_data = json.dumps(data)
  File "C:\Python27\Lib\json\__init__.py", line 244, in dumps
    return _default_encoder.encode(obj)
  File "C:\Python27\Lib\json\encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Python27\Lib\json\encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
  File "C:\Python27\Lib\json\encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: <htmlparser.Parser object at 0x05ECF930> is not JSON serializable
[2020-08-10 20:03:48,607] [ERROR] [buffer.py] [87] - json.dumps:<htmlparser.Parser object at 0x05ECC8B0> is not JSON serializable
Traceback (most recent call last):
  File "F:\spider\data_buffer\buffer.py", line 82, in pushall
    dest_data = json.dumps(data)
  File "C:\Python27\Lib\json\__init__.py", line 244, in dumps
    return _default_encoder.encode(obj)
  File "C:\Python27\Lib\json\encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Python27\Lib\json\encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
  File "C:\Python27\Lib\json\encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: <htmlparser.Parser object at 0x05ECC8B0> is not JSON serializable
[2020-08-10 20:03:48,637] [ERROR] [buffer.py] [87] - json.dumps:<htmlparser.Parser object at 0x046A0EB0> is not JSON serializable
Traceback (most recent call last):
  File "F:\spider\data_buffer\buffer.py", line 82, in pushall
    dest_data = json.dumps(data)
  File "C:\Python27\Lib\json\__init__.py", line 244, in dumps
    return _default_encoder.encode(obj)
  File "C:\Python27\Lib\json\encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Python27\Lib\json\encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
  File "C:\Python27\Lib\json\encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: <htmlparser.Parser object at 0x046A0EB0> is not JSON serializable
[2020-08-10 20:03:48,710] [ERROR] [buffer.py] [87] - json.dumps:<htmlparser.Parser object at 0x05ECC8B0> is not JSON serializable
Traceback (most recent call last):
  File "F:\spider\data_buffer\buffer.py", line 82, in pushall
    dest_data = json.dumps(data)
  File "C:\Python27\Lib\json\__init__.py", line 244, in dumps
    return _default_encoder.encode(obj)
  File "C:\Python27\Lib\json\encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Python27\Lib\json\encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
  File "C:\Python27\Lib\json\encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: <htmlparser.Parser object at 0x05ECC8B0> is not JSON serializable
[2020-08-10 20:03:49,046] [ERROR] [buffer.py] [87] - json.dumps:<htmlparser.Parser object at 0x05758650> is not JSON serializable
Traceback (most recent call last):
  File "F:\spider\data_buffer\buffer.py", line 82, in pushall
    dest_data = json.dumps(data)
  File "C:\Python27\Lib\json\__init__.py", line 244, in dumps
    return _default_encoder.encode(obj)
  File "C:\Python27\Lib\json\encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Python27\Lib\json\encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
  File "C:\Python27\Lib\json\encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: <htmlparser.Parser object at 0x05758650> is not JSON serializable
[2020-08-10 20:03:49,319] [ERROR] [buffer.py] [87] - json.dumps:<htmlparser.Parser object at 0x05ECC450> is not JSON serializable
Traceback (most recent call last):
  File "F:\spider\data_buffer\buffer.py", line 82, in pushall
    dest_data = json.dumps(data)
  File "C:\Python27\Lib\json\__init__.py", line 244, in dumps
    return _default_encoder.encode(obj)
  File "C:\Python27\Lib\json\encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Python27\Lib\json\encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
  File "C:\Python27\Lib\json\encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: <htmlparser.Parser object at 0x05ECC450> is not JSON serializable
[2020-08-10 20:03:50,230] [ERROR] [buffer.py] [87] - json.dumps:<htmlparser.Parser object at 0x05EDF210> is not JSON serializable
Traceback (most recent call last):
  File "F:\spider\data_buffer\buffer.py", line 82, in pushall
    dest_data = json.dumps(data)
  File "C:\Python27\Lib\json\__init__.py", line 244, in dumps
    return _default_encoder.encode(obj)
  File "C:\Python27\Lib\json\encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Python27\Lib\json\encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
  File "C:\Python27\Lib\json\encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: <htmlparser.Parser object at 0x05EDF210> is not JSON serializable
[2020-08-10 20:03:50,286] [ERROR] [buffer.py] [87] - json.dumps:<htmlparser.Parser object at 0x05758890> is not JSON serializable
Traceback (most recent call last):
  File "F:\spider\data_buffer\buffer.py", line 82, in pushall
    dest_data = json.dumps(data)
  File "C:\Python27\Lib\json\__init__.py", line 244, in dumps
    return _default_encoder.encode(obj)
  File "C:\Python27\Lib\json\encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Python27\Lib\json\encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
  File "C:\Python27\Lib\json\encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: <htmlparser.Parser object at 0x05758890> is not JSON serializable
[2020-08-10 20:03:50,566] [ERROR] [buffer.py] [87] - json.dumps:<htmlparser.Parser object at 0x05ECC9F0> is not JSON serializable
Traceback (most recent call last):
  File "F:\spider\data_buffer\buffer.py", line 82, in pushall
    dest_data = json.dumps(data)
  File "C:\Python27\Lib\json\__init__.py", line 244, in dumps
    return _default_encoder.encode(obj)
  File "C:\Python27\Lib\json\encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Python27\Lib\json\encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
  File "C:\Python27\Lib\json\encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: <htmlparser.Parser object at 0x05ECC9F0> is not JSON serializable
[2020-08-10 20:03:50,806] [ERROR] [buffer.py] [87] - json.dumps:<htmlparser.Parser object at 0x05ECC830> is not JSON serializable
Traceback (most recent call last):
  File "F:\spider\data_buffer\buffer.py", line 82, in pushall
    dest_data = json.dumps(data)
  File "C:\Python27\Lib\json\__init__.py", line 244, in dumps
    return _default_encoder.encode(obj)
  File "C:\Python27\Lib\json\encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Python27\Lib\json\encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
  File "C:\Python27\Lib\json\encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: <htmlparser.Parser object at 0x05ECC830> is not JSON serializable
[2020-08-10 20:03:51,019] [ERROR] [buffer.py] [87] - json.dumps:<htmlparser.Parser object at 0x05ECCDB0> is not JSON serializable
Traceback (most recent call last):
  File "F:\spider\data_buffer\buffer.py", line 82, in pushall
    dest_data = json.dumps(data)
  File "C:\Python27\Lib\json\__init__.py", line 244, in dumps
    return _default_encoder.encode(obj)
  File "C:\Python27\Lib\json\encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Python27\Lib\json\encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
  File "C:\Python27\Lib\json\encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: <htmlparser.Parser object at 0x05ECCDB0> is not JSON serializable
[2020-08-10 20:03:51,624] [ERROR] [buffer.py] [87] - json.dumps:<htmlparser.Parser object at 0x05ECF330> is not JSON serializable
Traceback (most recent call last):
  File "F:\spider\data_buffer\buffer.py", line 82, in pushall
    dest_data = json.dumps(data)
  File "C:\Python27\Lib\json\__init__.py", line 244, in dumps
    return _default_encoder.encode(obj)
  File "C:\Python27\Lib\json\encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Python27\Lib\json\encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
  File "C:\Python27\Lib\json\encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: <htmlparser.Parser object at 0x05ECF330> is not JSON serializable
[2020-08-10 20:03:51,654] [ERROR] [buffer.py] [87] - json.dumps:<htmlparser.Parser object at 0x057585D0> is not JSON serializable
Traceback (most recent call last):
  File "F:\spider\data_buffer\buffer.py", line 82, in pushall
    dest_data = json.dumps(data)
  File "C:\Python27\Lib\json\__init__.py", line 244, in dumps
    return _default_encoder.encode(obj)
  File "C:\Python27\Lib\json\encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Python27\Lib\json\encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
  File "C:\Python27\Lib\json\encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: <htmlparser.Parser object at 0x057585D0> is not JSON serializable
[2020-08-10 20:03:51,678] [ERROR] [buffer.py] [87] - json.dumps:<htmlparser.Parser object at 0x05ECF490> is not JSON serializable
Traceback (most recent call last):
  File "F:\spider\data_buffer\buffer.py", line 82, in pushall
    dest_data = json.dumps(data)
  File "C:\Python27\Lib\json\__init__.py", line 244, in dumps
    return _default_encoder.encode(obj)
  File "C:\Python27\Lib\json\encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Python27\Lib\json\encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
  File "C:\Python27\Lib\json\encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: <htmlparser.Parser object at 0x05ECF490> is not JSON serializable
[2020-08-10 20:03:51,724] [ERROR] [buffer.py] [87] - json.dumps:<htmlparser.Parser object at 0x057585D0> is not JSON serializable
Traceback (most recent call last):
  File "F:\spider\data_buffer\buffer.py", line 82, in pushall
    dest_data = json.dumps(data)
  File "C:\Python27\Lib\json\__init__.py", line 244, in dumps
    return _default_encoder.encode(obj)
  File "C:\Python27\Lib\json\encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Python27\Lib\json\encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
  File "C:\Python27\Lib\json\encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: <htmlparser.Parser object at 0x057585D0> is not JSON serializable
[2020-08-10 20:03:52,275] [ERROR] [buffer.py] [87] - json.dumps:<htmlparser.Parser object at 0x05782AD0> is not JSON serializable
Traceback (most recent call last):
  File "F:\spider\data_buffer\buffer.py", line 82, in pushall
    dest_data = json.dumps(data)
  File "C:\Python27\Lib\json\__init__.py", line 244, in dumps
    return _default_encoder.encode(obj)
  File "C:\Python27\Lib\json\encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Python27\Lib\json\encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
  File "C:\Python27\Lib\json\encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: <htmlparser.Parser object at 0x05782AD0> is not JSON serializable
[2020-08-10 20:03:53,328] [ERROR] [buffer.py] [87] - json.dumps:<htmlparser.Parser object at 0x05ECFDF0> is not JSON serializable
Traceback (most recent call last):
  File "F:\spider\data_buffer\buffer.py", line 82, in pushall
    dest_data = json.dumps(data)
  File "C:\Python27\Lib\json\__init__.py", line 244, in dumps
    return _default_encoder.encode(obj)
  File "C:\Python27\Lib\json\encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Python27\Lib\json\encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
  File "C:\Python27\Lib\json\encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: <htmlparser.Parser object at 0x05ECFDF0> is not JSON serializable
[2020-08-10 20:03:53,371] [ERROR] [buffer.py] [87] - json.dumps:<htmlparser.Parser object at 0x05ECCA70> is not JSON serializable
Traceback (most recent call last):
  File "F:\spider\data_buffer\buffer.py", line 82, in pushall
    dest_data = json.dumps(data)
  File "C:\Python27\Lib\json\__init__.py", line 244, in dumps
    return _default_encoder.encode(obj)
  File "C:\Python27\Lib\json\encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Python27\Lib\json\encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
  File "C:\Python27\Lib\json\encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: <htmlparser.Parser object at 0x05ECCA70> is not JSON serializable
[2020-08-10 20:03:53,473] [ERROR] [buffer.py] [87] - json.dumps:<htmlparser.Parser object at 0x05ECCEF0> is not JSON serializable
Traceback (most recent call last):
  File "F:\spider\data_buffer\buffer.py", line 82, in pushall
    dest_data = json.dumps(data)
  File "C:\Python27\Lib\json\__init__.py", line 244, in dumps
    return _default_encoder.encode(obj)
  File "C:\Python27\Lib\json\encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Python27\Lib\json\encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
  File "C:\Python27\Lib\json\encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: <htmlparser.Parser object at 0x05ECCEF0> is not JSON serializable
[2020-08-10 20:03:53,634] [ERROR] [buffer.py] [87] - json.dumps:<htmlparser.Parser object at 0x05ECCDB0> is not JSON serializable
Traceback (most recent call last):
  File "F:\spider\data_buffer\buffer.py", line 82, in pushall
    dest_data = json.dumps(data)
  File "C:\Python27\Lib\json\__init__.py", line 244, in dumps
    return _default_encoder.encode(obj)
  File "C:\Python27\Lib\json\encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Python27\Lib\json\encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
  File "C:\Python27\Lib\json\encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: <htmlparser.Parser object at 0x05ECCDB0> is not JSON serializable
[2020-08-10 20:03:53,819] [ERROR] [buffer.py] [87] - json.dumps:<htmlparser.Parser object at 0x0577A230> is not JSON serializable
Traceback (most recent call last):
  File "F:\spider\data_buffer\buffer.py", line 82, in pushall
    dest_data = json.dumps(data)
  File "C:\Python27\Lib\json\__init__.py", line 244, in dumps
    return _default_encoder.encode(obj)
  File "C:\Python27\Lib\json\encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Python27\Lib\json\encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
  File "C:\Python27\Lib\json\encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: <htmlparser.Parser object at 0x0577A230> is not JSON serializable
[2020-08-10 20:03:55,128] [ERROR] [buffer.py] [87] - json.dumps:<htmlparser.Parser object at 0x05EDFC10> is not JSON serializable
Traceback (most recent call last):
  File "F:\spider\data_buffer\buffer.py", line 82, in pushall
    dest_data = json.dumps(data)
  File "C:\Python27\Lib\json\__init__.py", line 244, in dumps
    return _default_encoder.encode(obj)
  File "C:\Python27\Lib\json\encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Python27\Lib\json\encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
  File "C:\Python27\Lib\json\encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: <htmlparser.Parser object at 0x05EDFC10> is not JSON serializable
[2020-08-10 20:03:55,160] [ERROR] [buffer.py] [87] - json.dumps:<htmlparser.Parser object at 0x047FFA90> is not JSON serializable
Traceback (most recent call last):
  File "F:\spider\data_buffer\buffer.py", line 82, in pushall
    dest_data = json.dumps(data)
  File "C:\Python27\Lib\json\__init__.py", line 244, in dumps
    return _default_encoder.encode(obj)
  File "C:\Python27\Lib\json\encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Python27\Lib\json\encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
  File "C:\Python27\Lib\json\encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: <htmlparser.Parser object at 0x047FFA90> is not JSON serializable
[2020-08-10 20:03:55,196] [ERROR] [buffer.py] [87] - json.dumps:<htmlparser.Parser object at 0x047FF910> is not JSON serializable
Traceback (most recent call last):
  File "F:\spider\data_buffer\buffer.py", line 82, in pushall
    dest_data = json.dumps(data)
  File "C:\Python27\Lib\json\__init__.py", line 244, in dumps
    return _default_encoder.encode(obj)
  File "C:\Python27\Lib\json\encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Python27\Lib\json\encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
  File "C:\Python27\Lib\json\encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: <htmlparser.Parser object at 0x047FF910> is not JSON serializable
[2020-08-10 20:03:55,227] [ERROR] [buffer.py] [87] - json.dumps:<htmlparser.Parser object at 0x0577A7F0> is not JSON serializable
Traceback (most recent call last):
  File "F:\spider\data_buffer\buffer.py", line 82, in pushall
    dest_data = json.dumps(data)
  File "C:\Python27\Lib\json\__init__.py", line 244, in dumps
    return _default_encoder.encode(obj)
  File "C:\Python27\Lib\json\encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Python27\Lib\json\encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
  File "C:\Python27\Lib\json\encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: <htmlparser.Parser object at 0x0577A7F0> is not JSON serializable
[2020-08-10 20:03:55,512] [ERROR] [buffer.py] [87] - json.dumps:<htmlparser.Parser object at 0x05EDF330> is not JSON serializable
Traceback (most recent call last):
  File "F:\spider\data_buffer\buffer.py", line 82, in pushall
    dest_data = json.dumps(data)
  File "C:\Python27\Lib\json\__init__.py", line 244, in dumps
    return _default_encoder.encode(obj)
  File "C:\Python27\Lib\json\encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Python27\Lib\json\encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
  File "C:\Python27\Lib\json\encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: <htmlparser.Parser object at 0x05EDF330> is not JSON serializable
[2020-08-10 20:03:57,377] [ERROR] [buffer.py] [87] - json.dumps:<htmlparser.Parser object at 0x05EDF5F0> is not JSON serializable
Traceback (most recent call last):
  File "F:\spider\data_buffer\buffer.py", line 82, in pushall
    dest_data = json.dumps(data)
  File "C:\Python27\Lib\json\__init__.py", line 244, in dumps
    return _default_encoder.encode(obj)
  File "C:\Python27\Lib\json\encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Python27\Lib\json\encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
  File "C:\Python27\Lib\json\encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: <htmlparser.Parser object at 0x05EDF5F0> is not JSON serializable
[2020-08-10 20:03:57,401] [ERROR] [buffer.py] [87] - json.dumps:<htmlparser.Parser object at 0x05758550> is not JSON serializable
Traceback (most recent call last):
  File "F:\spider\data_buffer\buffer.py", line 82, in pushall
    dest_data = json.dumps(data)
  File "C:\Python27\Lib\json\__init__.py", line 244, in dumps
    return _default_encoder.encode(obj)
  File "C:\Python27\Lib\json\encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Python27\Lib\json\encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
  File "C:\Python27\Lib\json\encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: <htmlparser.Parser object at 0x05758550> is not JSON serializable
[2020-08-10 20:03:57,473] [ERROR] [buffer.py] [87] - json.dumps:<htmlparser.Parser object at 0x057583F0> is not JSON serializable
Traceback (most recent call last):
  File "F:\spider\data_buffer\buffer.py", line 82, in pushall
    dest_data = json.dumps(data)
  File "C:\Python27\Lib\json\__init__.py", line 244, in dumps
    return _default_encoder.encode(obj)
  File "C:\Python27\Lib\json\encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Python27\Lib\json\encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
  File "C:\Python27\Lib\json\encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: <htmlparser.Parser object at 0x057583F0> is not JSON serializable
[2020-08-10 20:03:57,542] [ERROR] [buffer.py] [87] - json.dumps:<htmlparser.Parser object at 0x047FFA70> is not JSON serializable
Traceback (most recent call last):
  File "F:\spider\data_buffer\buffer.py", line 82, in pushall
    dest_data = json.dumps(data)
  File "C:\Python27\Lib\json\__init__.py", line 244, in dumps
    return _default_encoder.encode(obj)
  File "C:\Python27\Lib\json\encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Python27\Lib\json\encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
  File "C:\Python27\Lib\json\encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: <htmlparser.Parser object at 0x047FFA70> is not JSON serializable
[2020-08-10 20:03:57,910] [ERROR] [buffer.py] [87] - json.dumps:<htmlparser.Parser object at 0x05ECC850> is not JSON serializable
Traceback (most recent call last):
  File "F:\spider\data_buffer\buffer.py", line 82, in pushall
    dest_data = json.dumps(data)
  File "C:\Python27\Lib\json\__init__.py", line 244, in dumps
    return _default_encoder.encode(obj)
  File "C:\Python27\Lib\json\encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Python27\Lib\json\encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
  File "C:\Python27\Lib\json\encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: <htmlparser.Parser object at 0x05ECC850> is not JSON serializable
[2020-08-10 20:03:59,724] [ERROR] [buffer.py] [87] - json.dumps:<htmlparser.Parser object at 0x05EDF510> is not JSON serializable
Traceback (most recent call last):
  File "F:\spider\data_buffer\buffer.py", line 82, in pushall
    dest_data = json.dumps(data)
  File "C:\Python27\Lib\json\__init__.py", line 244, in dumps
    return _default_encoder.encode(obj)
  File "C:\Python27\Lib\json\encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Python27\Lib\json\encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
  File "C:\Python27\Lib\json\encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: <htmlparser.Parser object at 0x05EDF510> is not JSON serializable
[2020-08-10 20:03:59,765] [ERROR] [buffer.py] [87] - json.dumps:<htmlparser.Parser object at 0x047FF9D0> is not JSON serializable
Traceback (most recent call last):
  File "F:\spider\data_buffer\buffer.py", line 82, in pushall
    dest_data = json.dumps(data)
  File "C:\Python27\Lib\json\__init__.py", line 244, in dumps
    return _default_encoder.encode(obj)
  File "C:\Python27\Lib\json\encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Python27\Lib\json\encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
  File "C:\Python27\Lib\json\encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: <htmlparser.Parser object at 0x047FF9D0> is not JSON serializable
[2020-08-10 20:03:59,940] [ERROR] [buffer.py] [87] - json.dumps:<htmlparser.Parser object at 0x05EDF130> is not JSON serializable
Traceback (most recent call last):
  File "F:\spider\data_buffer\buffer.py", line 82, in pushall
    dest_data = json.dumps(data)
  File "C:\Python27\Lib\json\__init__.py", line 244, in dumps
    return _default_encoder.encode(obj)
  File "C:\Python27\Lib\json\encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Python27\Lib\json\encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
  File "C:\Python27\Lib\json\encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: <htmlparser.Parser object at 0x05EDF130> is not JSON serializable
[2020-08-10 20:04:00,355] [ERROR] [buffer.py] [87] - json.dumps:<htmlparser.Parser object at 0x05ECCE10> is not JSON serializable
Traceback (most recent call last):
  File "F:\spider\data_buffer\buffer.py", line 82, in pushall
    dest_data = json.dumps(data)
  File "C:\Python27\Lib\json\__init__.py", line 244, in dumps
    return _default_encoder.encode(obj)
  File "C:\Python27\Lib\json\encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Python27\Lib\json\encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
  File "C:\Python27\Lib\json\encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: <htmlparser.Parser object at 0x05ECCE10> is not JSON serializable
[2020-08-10 20:04:00,865] [ERROR] [buffer.py] [87] - json.dumps:<htmlparser.Parser object at 0x05ECF450> is not JSON serializable
Traceback (most recent call last):
  File "F:\spider\data_buffer\buffer.py", line 82, in pushall
    dest_data = json.dumps(data)
  File "C:\Python27\Lib\json\__init__.py", line 244, in dumps
    return _default_encoder.encode(obj)
  File "C:\Python27\Lib\json\encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Python27\Lib\json\encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
  File "C:\Python27\Lib\json\encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: <htmlparser.Parser object at 0x05ECF450> is not JSON serializable
[2020-08-10 20:04:01,523] [ERROR] [buffer.py] [87] - json.dumps:<htmlparser.Parser object at 0x047FF9B0> is not JSON serializable
Traceback (most recent call last):
  File "F:\spider\data_buffer\buffer.py", line 82, in pushall
    dest_data = json.dumps(data)
  File "C:\Python27\Lib\json\__init__.py", line 244, in dumps
    return _default_encoder.encode(obj)
  File "C:\Python27\Lib\json\encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Python27\Lib\json\encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
  File "C:\Python27\Lib\json\encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: <htmlparser.Parser object at 0x047FF9B0> is not JSON serializable
[2020-08-10 20:04:01,654] [ERROR] [buffer.py] [87] - json.dumps:<htmlparser.Parser object at 0x05782130> is not JSON serializable
Traceback (most recent call last):
  File "F:\spider\data_buffer\buffer.py", line 82, in pushall
    dest_data = json.dumps(data)
  File "C:\Python27\Lib\json\__init__.py", line 244, in dumps
    return _default_encoder.encode(obj)
  File "C:\Python27\Lib\json\encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Python27\Lib\json\encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
  File "C:\Python27\Lib\json\encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: <htmlparser.Parser object at 0x05782130> is not JSON serializable
[2020-08-10 20:04:01,862] [ERROR] [buffer.py] [87] - json.dumps:<htmlparser.Parser object at 0x05ECCDD0> is not JSON serializable
Traceback (most recent call last):
  File "F:\spider\data_buffer\buffer.py", line 82, in pushall
    dest_data = json.dumps(data)
  File "C:\Python27\Lib\json\__init__.py", line 244, in dumps
    return _default_encoder.encode(obj)
  File "C:\Python27\Lib\json\encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Python27\Lib\json\encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
  File "C:\Python27\Lib\json\encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: <htmlparser.Parser object at 0x05ECCDD0> is not JSON serializable
[2020-08-10 20:04:02,042] [ERROR] [buffer.py] [87] - json.dumps:<htmlparser.Parser object at 0x055B9E10> is not JSON serializable
Traceback (most recent call last):
  File "F:\spider\data_buffer\buffer.py", line 82, in pushall
    dest_data = json.dumps(data)
  File "C:\Python27\Lib\json\__init__.py", line 244, in dumps
    return _default_encoder.encode(obj)
  File "C:\Python27\Lib\json\encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Python27\Lib\json\encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
  File "C:\Python27\Lib\json\encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: <htmlparser.Parser object at 0x055B9E10> is not JSON serializable
[2020-08-10 20:04:02,278] [ERROR] [buffer.py] [87] - json.dumps:<htmlparser.Parser object at 0x05EDFFB0> is not JSON serializable
Traceback (most recent call last):
  File "F:\spider\data_buffer\buffer.py", line 82, in pushall
    dest_data = json.dumps(data)
  File "C:\Python27\Lib\json\__init__.py", line 244, in dumps
    return _default_encoder.encode(obj)
  File "C:\Python27\Lib\json\encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Python27\Lib\json\encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
  File "C:\Python27\Lib\json\encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: <htmlparser.Parser object at 0x05EDFFB0> is not JSON serializable
[2020-08-10 20:04:02,993] [ERROR] [buffer.py] [87] - json.dumps:<htmlparser.Parser object at 0x05ECF550> is not JSON serializable
Traceback (most recent call last):
  File "F:\spider\data_buffer\buffer.py", line 82, in pushall
    dest_data = json.dumps(data)
  File "C:\Python27\Lib\json\__init__.py", line 244, in dumps
    return _default_encoder.encode(obj)
  File "C:\Python27\Lib\json\encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Python27\Lib\json\encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
  File "C:\Python27\Lib\json\encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: <htmlparser.Parser object at 0x05ECF550> is not JSON serializable
[2020-08-10 20:04:03,020] [ERROR] [buffer.py] [87] - json.dumps:<htmlparser.Parser object at 0x047E9070> is not JSON serializable
Traceback (most recent call last):
  File "F:\spider\data_buffer\buffer.py", line 82, in pushall
    dest_data = json.dumps(data)
  File "C:\Python27\Lib\json\__init__.py", line 244, in dumps
    return _default_encoder.encode(obj)
  File "C:\Python27\Lib\json\encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Python27\Lib\json\encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
  File "C:\Python27\Lib\json\encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: <htmlparser.Parser object at 0x047E9070> is not JSON serializable
[2020-08-10 20:04:03,411] [ERROR] [buffer.py] [87] - json.dumps:<htmlparser.Parser object at 0x055B9130> is not JSON serializable
Traceback (most recent call last):
  File "F:\spider\data_buffer\buffer.py", line 82, in pushall
    dest_data = json.dumps(data)
  File "C:\Python27\Lib\json\__init__.py", line 244, in dumps
    return _default_encoder.encode(obj)
  File "C:\Python27\Lib\json\encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Python27\Lib\json\encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
  File "C:\Python27\Lib\json\encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: <htmlparser.Parser object at 0x055B9130> is not JSON serializable
[2020-08-10 20:04:03,658] [ERROR] [buffer.py] [87] - json.dumps:<htmlparser.Parser object at 0x046AB350> is not JSON serializable
Traceback (most recent call last):
  File "F:\spider\data_buffer\buffer.py", line 82, in pushall
    dest_data = json.dumps(data)
  File "C:\Python27\Lib\json\__init__.py", line 244, in dumps
    return _default_encoder.encode(obj)
  File "C:\Python27\Lib\json\encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Python27\Lib\json\encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
  File "C:\Python27\Lib\json\encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: <htmlparser.Parser object at 0x046AB350> is not JSON serializable
[2020-08-10 20:04:03,984] [ERROR] [buffer.py] [87] - json.dumps:<htmlparser.Parser object at 0x05ECC2F0> is not JSON serializable
Traceback (most recent call last):
  File "F:\spider\data_buffer\buffer.py", line 82, in pushall
    dest_data = json.dumps(data)
  File "C:\Python27\Lib\json\__init__.py", line 244, in dumps
    return _default_encoder.encode(obj)
  File "C:\Python27\Lib\json\encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Python27\Lib\json\encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
  File "C:\Python27\Lib\json\encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: <htmlparser.Parser object at 0x05ECC2F0> is not JSON serializable
[2020-08-10 20:04:04,352] [ERROR] [buffer.py] [87] - json.dumps:<htmlparser.Parser object at 0x05ECF930> is not JSON serializable
Traceback (most recent call last):
  File "F:\spider\data_buffer\buffer.py", line 82, in pushall
    dest_data = json.dumps(data)
  File "C:\Python27\Lib\json\__init__.py", line 244, in dumps
    return _default_encoder.encode(obj)
  File "C:\Python27\Lib\json\encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Python27\Lib\json\encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
  File "C:\Python27\Lib\json\encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: <htmlparser.Parser object at 0x05ECF930> is not JSON serializable
[2020-08-10 20:04:04,394] [ERROR] [buffer.py] [87] - json.dumps:<htmlparser.Parser object at 0x057824D0> is not JSON serializable
Traceback (most recent call last):
  File "F:\spider\data_buffer\buffer.py", line 82, in pushall
    dest_data = json.dumps(data)
  File "C:\Python27\Lib\json\__init__.py", line 244, in dumps
    return _default_encoder.encode(obj)
  File "C:\Python27\Lib\json\encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Python27\Lib\json\encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
  File "C:\Python27\Lib\json\encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: <htmlparser.Parser object at 0x057824D0> is not JSON serializable
[2020-08-10 20:04:04,426] [ERROR] [buffer.py] [87] - json.dumps:<htmlparser.Parser object at 0x05ECF510> is not JSON serializable
Traceback (most recent call last):
  File "F:\spider\data_buffer\buffer.py", line 82, in pushall
    dest_data = json.dumps(data)
  File "C:\Python27\Lib\json\__init__.py", line 244, in dumps
    return _default_encoder.encode(obj)
  File "C:\Python27\Lib\json\encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Python27\Lib\json\encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
  File "C:\Python27\Lib\json\encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: <htmlparser.Parser object at 0x05ECF510> is not JSON serializable
[2020-08-10 20:04:04,471] [ERROR] [buffer.py] [87] - json.dumps:<htmlparser.Parser object at 0x05ECCA10> is not JSON serializable
Traceback (most recent call last):
  File "F:\spider\data_buffer\buffer.py", line 82, in pushall
    dest_data = json.dumps(data)
  File "C:\Python27\Lib\json\__init__.py", line 244, in dumps
    return _default_encoder.encode(obj)
  File "C:\Python27\Lib\json\encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Python27\Lib\json\encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
  File "C:\Python27\Lib\json\encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: <htmlparser.Parser object at 0x05ECCA10> is not JSON serializable
[2020-08-10 20:04:04,703] [ERROR] [buffer.py] [87] - json.dumps:<htmlparser.Parser object at 0x05782370> is not JSON serializable
Traceback (most recent call last):
  File "F:\spider\data_buffer\buffer.py", line 82, in pushall
    dest_data = json.dumps(data)
  File "C:\Python27\Lib\json\__init__.py", line 244, in dumps
    return _default_encoder.encode(obj)
  File "C:\Python27\Lib\json\encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Python27\Lib\json\encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
  File "C:\Python27\Lib\json\encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: <htmlparser.Parser object at 0x05782370> is not JSON serializable
[2020-08-10 20:04:06,171] [ERROR] [buffer.py] [87] - json.dumps:<htmlparser.Parser object at 0x05EDF1B0> is not JSON serializable
Traceback (most recent call last):
  File "F:\spider\data_buffer\buffer.py", line 82, in pushall
    dest_data = json.dumps(data)
  File "C:\Python27\Lib\json\__init__.py", line 244, in dumps
    return _default_encoder.encode(obj)
  File "C:\Python27\Lib\json\encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Python27\Lib\json\encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
  File "C:\Python27\Lib\json\encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: <htmlparser.Parser object at 0x05EDF1B0> is not JSON serializable
[2020-08-10 20:04:06,253] [ERROR] [buffer.py] [87] - json.dumps:<htmlparser.Parser object at 0x05ED3BD0> is not JSON serializable
Traceback (most recent call last):
  File "F:\spider\data_buffer\buffer.py", line 82, in pushall
    dest_data = json.dumps(data)
  File "C:\Python27\Lib\json\__init__.py", line 244, in dumps
    return _default_encoder.encode(obj)
  File "C:\Python27\Lib\json\encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Python27\Lib\json\encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
  File "C:\Python27\Lib\json\encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: <htmlparser.Parser object at 0x05ED3BD0> is not JSON serializable
[2020-08-10 20:04:06,457] [ERROR] [buffer.py] [87] - json.dumps:<htmlparser.Parser object at 0x0577AE90> is not JSON serializable
Traceback (most recent call last):
  File "F:\spider\data_buffer\buffer.py", line 82, in pushall
    dest_data = json.dumps(data)
  File "C:\Python27\Lib\json\__init__.py", line 244, in dumps
    return _default_encoder.encode(obj)
  File "C:\Python27\Lib\json\encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Python27\Lib\json\encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
  File "C:\Python27\Lib\json\encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: <htmlparser.Parser object at 0x0577AE90> is not JSON serializable
[2020-08-10 20:04:06,664] [ERROR] [buffer.py] [87] - json.dumps:<htmlparser.Parser object at 0x05ED3150> is not JSON serializable
Traceback (most recent call last):
  File "F:\spider\data_buffer\buffer.py", line 82, in pushall
    dest_data = json.dumps(data)
  File "C:\Python27\Lib\json\__init__.py", line 244, in dumps
    return _default_encoder.encode(obj)
  File "C:\Python27\Lib\json\encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Python27\Lib\json\encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
  File "C:\Python27\Lib\json\encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: <htmlparser.Parser object at 0x05ED3150> is not JSON serializable
[2020-08-10 20:04:06,872] [ERROR] [buffer.py] [87] - json.dumps:<htmlparser.Parser object at 0x047FFB30> is not JSON serializable
Traceback (most recent call last):
  File "F:\spider\data_buffer\buffer.py", line 82, in pushall
    dest_data = json.dumps(data)
  File "C:\Python27\Lib\json\__init__.py", line 244, in dumps
    return _default_encoder.encode(obj)
  File "C:\Python27\Lib\json\encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Python27\Lib\json\encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
  File "C:\Python27\Lib\json\encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: <htmlparser.Parser object at 0x047FFB30> is not JSON serializable
[2020-08-10 20:04:08,148] [ERROR] [buffer.py] [87] - json.dumps:<htmlparser.Parser object at 0x047F5DB0> is not JSON serializable
Traceback (most recent call last):
  File "F:\spider\data_buffer\buffer.py", line 82, in pushall
    dest_data = json.dumps(data)
  File "C:\Python27\Lib\json\__init__.py", line 244, in dumps
    return _default_encoder.encode(obj)
  File "C:\Python27\Lib\json\encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Python27\Lib\json\encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
  File "C:\Python27\Lib\json\encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: <htmlparser.Parser object at 0x047F5DB0> is not JSON serializable
[2020-08-10 20:04:08,234] [ERROR] [buffer.py] [87] - json.dumps:<htmlparser.Parser object at 0x055B9130> is not JSON serializable
Traceback (most recent call last):
  File "F:\spider\data_buffer\buffer.py", line 82, in pushall
    dest_data = json.dumps(data)
  File "C:\Python27\Lib\json\__init__.py", line 244, in dumps
    return _default_encoder.encode(obj)
  File "C:\Python27\Lib\json\encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Python27\Lib\json\encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
  File "C:\Python27\Lib\json\encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: <htmlparser.Parser object at 0x055B9130> is not JSON serializable
[2020-08-10 20:04:08,582] [ERROR] [buffer.py] [87] - json.dumps:<htmlparser.Parser object at 0x05EDF510> is not JSON serializable
Traceback (most recent call last):
  File "F:\spider\data_buffer\buffer.py", line 82, in pushall
    dest_data = json.dumps(data)
  File "C:\Python27\Lib\json\__init__.py", line 244, in dumps
    return _default_encoder.encode(obj)
  File "C:\Python27\Lib\json\encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Python27\Lib\json\encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
  File "C:\Python27\Lib\json\encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: <htmlparser.Parser object at 0x05EDF510> is not JSON serializable
[2020-08-10 20:04:08,773] [ERROR] [buffer.py] [87] - json.dumps:<htmlparser.Parser object at 0x0577A2F0> is not JSON serializable
Traceback (most recent call last):
  File "F:\spider\data_buffer\buffer.py", line 82, in pushall
    dest_data = json.dumps(data)
  File "C:\Python27\Lib\json\__init__.py", line 244, in dumps
    return _default_encoder.encode(obj)
  File "C:\Python27\Lib\json\encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Python27\Lib\json\encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
  File "C:\Python27\Lib\json\encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: <htmlparser.Parser object at 0x0577A2F0> is not JSON serializable
[2020-08-10 20:04:08,950] [ERROR] [buffer.py] [87] - json.dumps:<htmlparser.Parser object at 0x05515E10> is not JSON serializable
Traceback (most recent call last):
  File "F:\spider\data_buffer\buffer.py", line 82, in pushall
    dest_data = json.dumps(data)
  File "C:\Python27\Lib\json\__init__.py", line 244, in dumps
    return _default_encoder.encode(obj)
  File "C:\Python27\Lib\json\encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Python27\Lib\json\encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
  File "C:\Python27\Lib\json\encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: <htmlparser.Parser object at 0x05515E10> is not JSON serializable
[2020-08-10 20:04:10,263] [ERROR] [buffer.py] [87] - json.dumps:<htmlparser.Parser object at 0x05ED3470> is not JSON serializable
Traceback (most recent call last):
  File "F:\spider\data_buffer\buffer.py", line 82, in pushall
    dest_data = json.dumps(data)
  File "C:\Python27\Lib\json\__init__.py", line 244, in dumps
    return _default_encoder.encode(obj)
  File "C:\Python27\Lib\json\encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Python27\Lib\json\encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
  File "C:\Python27\Lib\json\encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: <htmlparser.Parser object at 0x05ED3470> is not JSON serializable
[2020-08-10 20:04:10,354] [ERROR] [buffer.py] [87] - json.dumps:<htmlparser.Parser object at 0x05ED34F0> is not JSON serializable
Traceback (most recent call last):
  File "F:\spider\data_buffer\buffer.py", line 82, in pushall
    dest_data = json.dumps(data)
  File "C:\Python27\Lib\json\__init__.py", line 244, in dumps
    return _default_encoder.encode(obj)
  File "C:\Python27\Lib\json\encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Python27\Lib\json\encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
  File "C:\Python27\Lib\json\encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: <htmlparser.Parser object at 0x05ED34F0> is not JSON serializable
[2020-08-10 20:04:10,802] [ERROR] [buffer.py] [87] - json.dumps:<htmlparser.Parser object at 0x0577AE30> is not JSON serializable
Traceback (most recent call last):
  File "F:\spider\data_buffer\buffer.py", line 82, in pushall
    dest_data = json.dumps(data)
  File "C:\Python27\Lib\json\__init__.py", line 244, in dumps
    return _default_encoder.encode(obj)
  File "C:\Python27\Lib\json\encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Python27\Lib\json\encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
  File "C:\Python27\Lib\json\encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: <htmlparser.Parser object at 0x0577AE30> is not JSON serializable
[2020-08-10 20:04:11,167] [ERROR] [buffer.py] [87] - json.dumps:<htmlparser.Parser object at 0x055B9070> is not JSON serializable
Traceback (most recent call last):
  File "F:\spider\data_buffer\buffer.py", line 82, in pushall
    dest_data = json.dumps(data)
  File "C:\Python27\Lib\json\__init__.py", line 244, in dumps
    return _default_encoder.encode(obj)
  File "C:\Python27\Lib\json\encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Python27\Lib\json\encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
  File "C:\Python27\Lib\json\encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: <htmlparser.Parser object at 0x055B9070> is not JSON serializable
[2020-08-10 20:04:11,427] [ERROR] [buffer.py] [87] - json.dumps:<htmlparser.Parser object at 0x055B9150> is not JSON serializable
Traceback (most recent call last):
  File "F:\spider\data_buffer\buffer.py", line 82, in pushall
    dest_data = json.dumps(data)
  File "C:\Python27\Lib\json\__init__.py", line 244, in dumps
    return _default_encoder.encode(obj)
  File "C:\Python27\Lib\json\encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Python27\Lib\json\encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
  File "C:\Python27\Lib\json\encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: <htmlparser.Parser object at 0x055B9150> is not JSON serializable
[2020-08-10 20:04:12,444] [ERROR] [buffer.py] [87] - json.dumps:<htmlparser.Parser object at 0x05ED3D30> is not JSON serializable
Traceback (most recent call last):
  File "F:\spider\data_buffer\buffer.py", line 82, in pushall
    dest_data = json.dumps(data)
  File "C:\Python27\Lib\json\__init__.py", line 244, in dumps
    return _default_encoder.encode(obj)
  File "C:\Python27\Lib\json\encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Python27\Lib\json\encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
  File "C:\Python27\Lib\json\encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: <htmlparser.Parser object at 0x05ED3D30> is not JSON serializable
[2020-08-10 20:04:12,519] [ERROR] [buffer.py] [87] - json.dumps:<htmlparser.Parser object at 0x047F9090> is not JSON serializable
Traceback (most recent call last):
  File "F:\spider\data_buffer\buffer.py", line 82, in pushall
    dest_data = json.dumps(data)
  File "C:\Python27\Lib\json\__init__.py", line 244, in dumps
    return _default_encoder.encode(obj)
  File "C:\Python27\Lib\json\encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Python27\Lib\json\encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
  File "C:\Python27\Lib\json\encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: <htmlparser.Parser object at 0x047F9090> is not JSON serializable
[2020-08-10 20:04:12,586] [ERROR] [buffer.py] [87] - json.dumps:<htmlparser.Parser object at 0x05515390> is not JSON serializable
Traceback (most recent call last):
  File "F:\spider\data_buffer\buffer.py", line 82, in pushall
    dest_data = json.dumps(data)
  File "C:\Python27\Lib\json\__init__.py", line 244, in dumps
    return _default_encoder.encode(obj)
  File "C:\Python27\Lib\json\encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Python27\Lib\json\encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
  File "C:\Python27\Lib\json\encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: <htmlparser.Parser object at 0x05515390> is not JSON serializable
[2020-08-10 20:04:12,855] [ERROR] [buffer.py] [87] - json.dumps:<htmlparser.Parser object at 0x055B9650> is not JSON serializable
Traceback (most recent call last):
  File "F:\spider\data_buffer\buffer.py", line 82, in pushall
    dest_data = json.dumps(data)
  File "C:\Python27\Lib\json\__init__.py", line 244, in dumps
    return _default_encoder.encode(obj)
  File "C:\Python27\Lib\json\encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Python27\Lib\json\encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
  File "C:\Python27\Lib\json\encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: <htmlparser.Parser object at 0x055B9650> is not JSON serializable
[2020-08-10 20:04:13,000] [ERROR] [buffer.py] [87] - json.dumps:<htmlparser.Parser object at 0x05ED31B0> is not JSON serializable
Traceback (most recent call last):
  File "F:\spider\data_buffer\buffer.py", line 82, in pushall
    dest_data = json.dumps(data)
  File "C:\Python27\Lib\json\__init__.py", line 244, in dumps
    return _default_encoder.encode(obj)
  File "C:\Python27\Lib\json\encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Python27\Lib\json\encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
  File "C:\Python27\Lib\json\encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: <htmlparser.Parser object at 0x05ED31B0> is not JSON serializable
[2020-08-10 20:04:14,431] [ERROR] [buffer.py] [87] - json.dumps:<htmlparser.Parser object at 0x057826F0> is not JSON serializable
Traceback (most recent call last):
  File "F:\spider\data_buffer\buffer.py", line 82, in pushall
    dest_data = json.dumps(data)
  File "C:\Python27\Lib\json\__init__.py", line 244, in dumps
    return _default_encoder.encode(obj)
  File "C:\Python27\Lib\json\encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Python27\Lib\json\encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
  File "C:\Python27\Lib\json\encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: <htmlparser.Parser object at 0x057826F0> is not JSON serializable
[2020-08-10 20:04:14,500] [ERROR] [buffer.py] [87] - json.dumps:<htmlparser.Parser object at 0x042A6FB0> is not JSON serializable
Traceback (most recent call last):
  File "F:\spider\data_buffer\buffer.py", line 82, in pushall
    dest_data = json.dumps(data)
  File "C:\Python27\Lib\json\__init__.py", line 244, in dumps
    return _default_encoder.encode(obj)
  File "C:\Python27\Lib\json\encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Python27\Lib\json\encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
  File "C:\Python27\Lib\json\encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: <htmlparser.Parser object at 0x042A6FB0> is not JSON serializable
[2020-08-10 20:04:14,562] [ERROR] [buffer.py] [87] - json.dumps:<htmlparser.Parser object at 0x05ED3A30> is not JSON serializable
Traceback (most recent call last):
  File "F:\spider\data_buffer\buffer.py", line 82, in pushall
    dest_data = json.dumps(data)
  File "C:\Python27\Lib\json\__init__.py", line 244, in dumps
    return _default_encoder.encode(obj)
  File "C:\Python27\Lib\json\encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Python27\Lib\json\encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
  File "C:\Python27\Lib\json\encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: <htmlparser.Parser object at 0x05ED3A30> is not JSON serializable
[2020-08-10 20:04:14,756] [ERROR] [buffer.py] [87] - json.dumps:<htmlparser.Parser object at 0x05782A30> is not JSON serializable
Traceback (most recent call last):
  File "F:\spider\data_buffer\buffer.py", line 82, in pushall
    dest_data = json.dumps(data)
  File "C:\Python27\Lib\json\__init__.py", line 244, in dumps
    return _default_encoder.encode(obj)
  File "C:\Python27\Lib\json\encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Python27\Lib\json\encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
  File "C:\Python27\Lib\json\encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: <htmlparser.Parser object at 0x05782A30> is not JSON serializable
[2020-08-10 20:04:14,950] [ERROR] [buffer.py] [87] - json.dumps:<htmlparser.Parser object at 0x057826D0> is not JSON serializable
Traceback (most recent call last):
  File "F:\spider\data_buffer\buffer.py", line 82, in pushall
    dest_data = json.dumps(data)
  File "C:\Python27\Lib\json\__init__.py", line 244, in dumps
    return _default_encoder.encode(obj)
  File "C:\Python27\Lib\json\encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Python27\Lib\json\encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
  File "C:\Python27\Lib\json\encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: <htmlparser.Parser object at 0x057826D0> is not JSON serializable
[2020-08-10 20:04:16,292] [ERROR] [buffer.py] [87] - json.dumps:<htmlparser.Parser object at 0x057822D0> is not JSON serializable
Traceback (most recent call last):
  File "F:\spider\data_buffer\buffer.py", line 82, in pushall
    dest_data = json.dumps(data)
  File "C:\Python27\Lib\json\__init__.py", line 244, in dumps
    return _default_encoder.encode(obj)
  File "C:\Python27\Lib\json\encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Python27\Lib\json\encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
  File "C:\Python27\Lib\json\encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: <htmlparser.Parser object at 0x057822D0> is not JSON serializable
[2020-08-10 20:04:16,315] [ERROR] [buffer.py] [87] - json.dumps:<htmlparser.Parser object at 0x047E9110> is not JSON serializable
Traceback (most recent call last):
  File "F:\spider\data_buffer\buffer.py", line 82, in pushall
    dest_data = json.dumps(data)
  File "C:\Python27\Lib\json\__init__.py", line 244, in dumps
    return _default_encoder.encode(obj)
  File "C:\Python27\Lib\json\encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Python27\Lib\json\encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
  File "C:\Python27\Lib\json\encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: <htmlparser.Parser object at 0x047E9110> is not JSON serializable
[2020-08-10 20:04:16,648] [ERROR] [buffer.py] [87] - json.dumps:<htmlparser.Parser object at 0x055B9770> is not JSON serializable
Traceback (most recent call last):
  File "F:\spider\data_buffer\buffer.py", line 82, in pushall
    dest_data = json.dumps(data)
  File "C:\Python27\Lib\json\__init__.py", line 244, in dumps
    return _default_encoder.encode(obj)
  File "C:\Python27\Lib\json\encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Python27\Lib\json\encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
  File "C:\Python27\Lib\json\encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: <htmlparser.Parser object at 0x055B9770> is not JSON serializable
[2020-08-10 20:04:16,875] [ERROR] [buffer.py] [87] - json.dumps:<htmlparser.Parser object at 0x0577A950> is not JSON serializable
Traceback (most recent call last):
  File "F:\spider\data_buffer\buffer.py", line 82, in pushall
    dest_data = json.dumps(data)
  File "C:\Python27\Lib\json\__init__.py", line 244, in dumps
    return _default_encoder.encode(obj)
  File "C:\Python27\Lib\json\encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Python27\Lib\json\encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
  File "C:\Python27\Lib\json\encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: <htmlparser.Parser object at 0x0577A950> is not JSON serializable
[2020-08-10 20:04:17,160] [ERROR] [buffer.py] [87] - json.dumps:<htmlparser.Parser object at 0x047FF990> is not JSON serializable
Traceback (most recent call last):
  File "F:\spider\data_buffer\buffer.py", line 82, in pushall
    dest_data = json.dumps(data)
  File "C:\Python27\Lib\json\__init__.py", line 244, in dumps
    return _default_encoder.encode(obj)
  File "C:\Python27\Lib\json\encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Python27\Lib\json\encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
  File "C:\Python27\Lib\json\encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: <htmlparser.Parser object at 0x047FF990> is not JSON serializable
[2020-08-10 20:04:17,957] [ERROR] [buffer.py] [87] - json.dumps:<htmlparser.Parser object at 0x05782BF0> is not JSON serializable
Traceback (most recent call last):
  File "F:\spider\data_buffer\buffer.py", line 82, in pushall
    dest_data = json.dumps(data)
  File "C:\Python27\Lib\json\__init__.py", line 244, in dumps
    return _default_encoder.encode(obj)
  File "C:\Python27\Lib\json\encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Python27\Lib\json\encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
  File "C:\Python27\Lib\json\encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: <htmlparser.Parser object at 0x05782BF0> is not JSON serializable
[2020-08-10 20:04:17,982] [ERROR] [buffer.py] [87] - json.dumps:<htmlparser.Parser object at 0x0577ABD0> is not JSON serializable
Traceback (most recent call last):
  File "F:\spider\data_buffer\buffer.py", line 82, in pushall
    dest_data = json.dumps(data)
  File "C:\Python27\Lib\json\__init__.py", line 244, in dumps
    return _default_encoder.encode(obj)
  File "C:\Python27\Lib\json\encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Python27\Lib\json\encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
  File "C:\Python27\Lib\json\encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: <htmlparser.Parser object at 0x0577ABD0> is not JSON serializable
[2020-08-10 20:04:18,053] [ERROR] [buffer.py] [87] - json.dumps:<htmlparser.Parser object at 0x0577AF10> is not JSON serializable
Traceback (most recent call last):
  File "F:\spider\data_buffer\buffer.py", line 82, in pushall
    dest_data = json.dumps(data)
  File "C:\Python27\Lib\json\__init__.py", line 244, in dumps
    return _default_encoder.encode(obj)
  File "C:\Python27\Lib\json\encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Python27\Lib\json\encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
  File "C:\Python27\Lib\json\encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: <htmlparser.Parser object at 0x0577AF10> is not JSON serializable
[2020-08-10 20:04:18,463] [ERROR] [buffer.py] [87] - json.dumps:<htmlparser.Parser object at 0x05782B50> is not JSON serializable
Traceback (most recent call last):
  File "F:\spider\data_buffer\buffer.py", line 82, in pushall
    dest_data = json.dumps(data)
  File "C:\Python27\Lib\json\__init__.py", line 244, in dumps
    return _default_encoder.encode(obj)
  File "C:\Python27\Lib\json\encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Python27\Lib\json\encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
  File "C:\Python27\Lib\json\encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: <htmlparser.Parser object at 0x05782B50> is not JSON serializable
[2020-08-10 20:04:18,789] [ERROR] [buffer.py] [87] - json.dumps:<htmlparser.Parser object at 0x05ED35D0> is not JSON serializable
Traceback (most recent call last):
  File "F:\spider\data_buffer\buffer.py", line 82, in pushall
    dest_data = json.dumps(data)
  File "C:\Python27\Lib\json\__init__.py", line 244, in dumps
    return _default_encoder.encode(obj)
  File "C:\Python27\Lib\json\encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Python27\Lib\json\encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
  File "C:\Python27\Lib\json\encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: <htmlparser.Parser object at 0x05ED35D0> is not JSON serializable
[2020-08-10 20:04:19,448] [ERROR] [buffer.py] [87] - json.dumps:<htmlparser.Parser object at 0x0577A510> is not JSON serializable
Traceback (most recent call last):
  File "F:\spider\data_buffer\buffer.py", line 82, in pushall
    dest_data = json.dumps(data)
  File "C:\Python27\Lib\json\__init__.py", line 244, in dumps
    return _default_encoder.encode(obj)
  File "C:\Python27\Lib\json\encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Python27\Lib\json\encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
  File "C:\Python27\Lib\json\encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: <htmlparser.Parser object at 0x0577A510> is not JSON serializable
[2020-08-10 20:04:19,470] [ERROR] [buffer.py] [87] - json.dumps:<htmlparser.Parser object at 0x05ED32D0> is not JSON serializable
Traceback (most recent call last):
  File "F:\spider\data_buffer\buffer.py", line 82, in pushall
    dest_data = json.dumps(data)
  File "C:\Python27\Lib\json\__init__.py", line 244, in dumps
    return _default_encoder.encode(obj)
  File "C:\Python27\Lib\json\encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Python27\Lib\json\encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
  File "C:\Python27\Lib\json\encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: <htmlparser.Parser object at 0x05ED32D0> is not JSON serializable
[2020-08-10 20:04:19,490] [ERROR] [buffer.py] [87] - json.dumps:<htmlparser.Parser object at 0x05758550> is not JSON serializable
Traceback (most recent call last):
  File "F:\spider\data_buffer\buffer.py", line 82, in pushall
    dest_data = json.dumps(data)
  File "C:\Python27\Lib\json\__init__.py", line 244, in dumps
    return _default_encoder.encode(obj)
  File "C:\Python27\Lib\json\encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Python27\Lib\json\encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
  File "C:\Python27\Lib\json\encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: <htmlparser.Parser object at 0x05758550> is not JSON serializable
[2020-08-10 20:04:19,509] [ERROR] [buffer.py] [87] - json.dumps:<htmlparser.Parser object at 0x057583F0> is not JSON serializable
Traceback (most recent call last):
  File "F:\spider\data_buffer\buffer.py", line 82, in pushall
    dest_data = json.dumps(data)
  File "C:\Python27\Lib\json\__init__.py", line 244, in dumps
    return _default_encoder.encode(obj)
  File "C:\Python27\Lib\json\encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Python27\Lib\json\encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
  File "C:\Python27\Lib\json\encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: <htmlparser.Parser object at 0x057583F0> is not JSON serializable
[2020-08-10 20:04:19,974] [ERROR] [buffer.py] [87] - json.dumps:<htmlparser.Parser object at 0x047FFA90> is not JSON serializable
Traceback (most recent call last):
  File "F:\spider\data_buffer\buffer.py", line 82, in pushall
    dest_data = json.dumps(data)
  File "C:\Python27\Lib\json\__init__.py", line 244, in dumps
    return _default_encoder.encode(obj)
  File "C:\Python27\Lib\json\encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Python27\Lib\json\encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
  File "C:\Python27\Lib\json\encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: <htmlparser.Parser object at 0x047FFA90> is not JSON serializable
